"""Render bilingual Markdown pages and a static SVG from validated content, deterministically."""

from __future__ import annotations

import posixpath
from datetime import date, timedelta
from xml.sax.saxutils import escape

from .content import STRENGTH, TRACKS, Content

LANGS = ("en", "ru")
HEADER = "<!-- Generated by scripts/build.py from src/content. Edit the YAML, not this file. -->"
MARKERS = {
    "official": "✅",
    "participant_report": "🗣",
    "prep_guide": "†",
    "secondary_compilation": "†",
}
SEGMENTS = (
    "frontier-lab",
    "big-tech",
    "ai-infra",
    "ai-native",
    "enterprise-ai",
    "fintech",
    "ru-big-tech",
)
SOURCE_KINDS = (
    "official",
    "participant_report",
    "prep_guide",
    "secondary_compilation",
    "reference",
)
COLORS = {"engineering": "#1f6feb", "leadership": "#bc4c00"}
LABELS = {
    "en": {
        "switch": "English · [Русский]({other})",
        "tagline": (
            "Sourced interview questions and interview loops for AI leadership — product "
            "managers, engineering managers, directors and technical programme managers — and "
            "for AI engineering. Every company claim and every reported question carries a "
            "source and the date it was read; questions written from job-posting themes are "
            "labelled as generated, and answers are written out rather than linked to a course."
        ),
        "stats": (
            "Questions: {questions} (engineering {engineering}, leadership {leadership}) · "
            "companies: {companies} · sources: {sources} · updated {updated}"
        ),
        "how": "How to use it",
        "how_items": [
            (
                "Pick your track: **{engineering}** or **{leadership}**. The track pages below list "
                "the roles each one covers."
            ),
            (
                "Work through *Start here* for your track, then the themes where the "
                "[requirements radar]({radar}) shows the most demand."
            ),
            (
                "Before an interview, open the company page: loop stages with their basis, the "
                "coding requirement and the questions reported for that company."
            ),
            (
                "Practise aloud. Every question says what it tests; priority questions also have "
                "answer checklists and reading. Use those as prompts for reasoning, not scripts."
            ),
        ],
        "how_items_no_radar": [
            (
                "Pick your track: **{engineering}** or **{leadership}**. The track pages below list "
                "the roles each one covers."
            ),
            "Work through *Start here* for your track, then the themes you expect in your loop.",
            (
                "Before an interview, open the company page: loop stages with their basis, the "
                "coding requirement and the questions reported for that company."
            ),
            (
                "Practise aloud. Every question says what it tests; priority questions also have "
                "answer checklists and reading. Use those as prompts for reasoning, not scripts."
            ),
        ],
        "legend": (
            "Markers: ✅ confirmed by the company · 🗣 candidate report · † prep guide or "
            "compilation without a first-hand source · 🧪 generated from job-posting themes. "
            "Interview loops change often, so check the retrieval date."
        ),
        "tracks": "Tracks and roles",
        "start": "Start here: {track}",
        "answers": "Answers: {track}",
        "answers_intro": (
            "Written answers to the priority questions of this track, in the same order and "
            "numbering as *Start here*. Answer each question yourself first: what follows is one "
            "good answer, not the only correct one, and an interviewer is listening to your "
            "reasoning rather than checking your wording."
        ),
        "answers_progress": "Answers written: {done} of {total}.",
        "answers_link": "[Answers to these questions]({page})",
        "common": "Asked across companies",
        "common_intro": "Questions reported at two or more companies, strongest basis first.",
        "themes": "Themes",
        "theme": "Theme",
        "companies": "Companies",
        "company": "Company",
        "segment": "Segment",
        "markets": "Markets",
        "coding": "Coding",
        "questions": "Questions",
        "reviewed": "Reviewed",
        "radar": "What job postings ask for",
        "radar_intro": (
            "Sample: {postings} postings ({start} to {end}). Percentages use each track's "
            "denominator: engineering n={engineering}, leadership n={leadership}. "
            "Tracks below n={min_track} are suppressed; a dash does not mean zero. "
            "[Method and full table]({page})."
        ),
        "about": "About",
        "about_items": [
            (
                "[Methodology]({methodology}): what counts as a source, how questions are "
                "written and what the markers mean."
            ),
            "[Sources and attribution]({sources}): every cited page with its retrieval date.",
            "[Attribution]({attribution}): upstream material, adaptations and licensing.",
            "[Contributing](CONTRIBUTING.md): add a question with a dated public source.",
            (
                "License: Apache-2.0 · © 2026 ai-interview-atlas contributors. Paraphrased "
                "material from licensed compilations is attributed on the sources page."
            ),
        ],
        "back": "← [AI Interview Atlas]({readme})",
        "asked_at": "Asked at",
        "tests": "Tests",
        "covers": "A strong answer covers",
        "read": "Read",
        "generated": "generated from job-posting themes",
        "both": "Both tracks",
        "roles": "Roles covered",
        "loop": "Interview loop",
        "stage": "Stage",
        "what": "What happens",
        "basis": "Basis",
        "prep": "Official preparation material",
        "reported": "Questions reported for {company}",
        "none_reported": "No company-specific questions are recorded yet.",
        "last_reviewed": "Loop reviewed {date}",
        "stale": "⚠️ older than a year",
        "radar_title": "Requirements radar",
        "period": "Period",
        "sample": "Sample",
        "sample_value": "{postings} postings: engineering {engineering}, leadership {leadership}",
        "market_value": "markets: international {intl}, Russia {ru}, unknown {unknown}",
        "method": "Method",
        "criteria": "What counts for each theme",
        "suppressed": (
            "A dash means fewer than {min_cell} postings mention the theme, or the track has "
            "fewer than {min_track} postings; such cells are not published."
        ),
        "share": "{share}% ({postings})",
        "sources_title": "Sources and attribution",
        "retrieved": "retrieved",
        "published": "published",
        "license": "license",
        "attribution": (
            "Questions marked † that come from {title} ({publisher}) are paraphrased and "
            "attributed to it; that compilation is licensed under {license}."
        ),
        "svg_title": "Share of postings that mention each theme",
        "ai_share": (
            "{track} postings in the sample: the role itself involves AI or machine "
            "learning in {share}% ({count} of {total})."
        ),
        "sample_names": {"engineering": "Engineering", "leadership": "Leadership"},
        "types": {
            "knowledge": "Knowledge",
            "coding": "Coding",
            "system_design": "System design",
            "product_case": "Product case",
            "applied_scenario": "Applied scenario",
            "leadership": "Leadership",
            "behavioral": "Behavioral",
            "self_presentation": "Self-presentation",
        },
        "levels": {"mid": "Mid", "senior": "Senior", "staff": "Staff+", "director": "Director+"},
        "segments": {
            "frontier-lab": "Frontier AI labs",
            "big-tech": "Big Tech",
            "ai-infra": "AI infrastructure",
            "ai-native": "AI-native products",
            "enterprise-ai": "Enterprise and forward-deployed AI",
            "fintech": "Fintech and payments",
            "ru-big-tech": "Russian Big Tech",
        },
        "market_names": {"intl": "International", "ru": "Russia"},
        "claims": {
            "confirmed": "✅ confirmed by the company",
            "participant_report": "🗣 candidate report",
            "secondary": "† prep guide or compilation",
            "assumption": "❔ assumption",
        },
        "coding_values": {
            "required": "required",
            "not_required": "not required",
            "varies": "varies by role",
            "unknown": "unknown",
        },
        "kinds": {
            "official": "Company sources",
            "participant_report": "Candidate reports",
            "prep_guide": "Preparation guides",
            "secondary_compilation": "Compilations",
            "reference": "Reference material",
        },
    },
    "ru": {
        "switch": "[English]({other}) · Русский",
        "tagline": (
            "Вопросы и этапы интервью с источниками — для AI-лидерства (продакт-менеджеры, "
            "руководители разработки, директора, руководители программ) и для AI-инженерии. "
            "У каждого утверждения о компании и каждого вопроса указаны источник и дата, когда "
            "его прочитали; вопросы, выведенные из тем вакансий, помечены как сгенерированные, "
            "а ответы написаны, а не заменены ссылкой на платный курс."
        ),
        "stats": (
            "Вопросов: {questions} (инженерия — {engineering}, лидерство — {leadership}) · "
            "компаний: {companies} · источников: {sources} · обновлено {updated}"
        ),
        "how": "Как пользоваться",
        "how_items": [
            (
                "Выберите трек: **{engineering}** или **{leadership}**. Ниже перечислены роли "
                "каждого трека."
            ),
            (
                "Пройдите раздел «С чего начать» своего трека, затем темы, которые чаще всего "
                "требуют вакансии по [радару требований]({radar})."
            ),
            (
                "Перед интервью откройте страницу компании: этапы с основаниями, требование к "
                "кодингу и вопросы, о которых сообщали для этой компании."
            ),
            (
                "Отвечайте вслух. Каждый вопрос объясняет, что проверяет; у приоритетных есть "
                "чек-листы ответа и чтение. Используйте их для рассуждений, а не заучивания."
            ),
        ],
        "how_items_no_radar": [
            (
                "Выберите трек: **{engineering}** или **{leadership}**. Ниже перечислены роли "
                "каждого трека."
            ),
            "Пройдите раздел «С чего начать» своего трека, затем темы, которые ждёте на интервью.",
            (
                "Перед интервью откройте страницу компании: этапы с основаниями, требование к "
                "кодингу и вопросы, о которых сообщали для этой компании."
            ),
            (
                "Отвечайте вслух. Каждый вопрос объясняет, что проверяет; у приоритетных есть "
                "чек-листы ответа и чтение. Используйте их для рассуждений, а не заучивания."
            ),
        ],
        "legend": (
            "Метки: ✅ подтверждено компанией · 🗣 отчёт кандидата · † гайд или подборка без "
            "первоисточника · 🧪 сгенерировано по темам вакансий. Этапы интервью часто "
            "меняются — смотрите дату проверки."
        ),
        "tracks": "Треки и роли",
        "start": "С чего начать: {track}",
        "answers": "Ответы: {track}",
        "answers_intro": (
            "Письменные ответы на приоритетные вопросы трека в том же порядке и нумерации, что и "
            "в разделе «С чего начать». Сначала ответьте сами: здесь один из хороших ответов, а "
            "не единственно верный, и интервьюер слушает ваши рассуждения, а не совпадение "
            "формулировок."
        ),
        "answers_progress": "Ответы готовы: {done} из {total}.",
        "answers_link": "[Ответы на эти вопросы]({page})",
        "common": "Спрашивают в нескольких компаниях",
        "common_intro": "Вопросы, о которых сообщали в двух и более компаниях; сильное основание — первым.",
        "themes": "Темы",
        "theme": "Тема",
        "companies": "Компании",
        "company": "Компания",
        "segment": "Сегмент",
        "markets": "Рынки",
        "coding": "Кодинг",
        "questions": "Вопросы",
        "reviewed": "Проверено",
        "radar": "Что требуют вакансии",
        "radar_intro": (
            "Выборка: {postings} вакансий ({start} — {end}). Проценты рассчитаны внутри "
            "каждого трека: инженерия n={engineering}, лидерство n={leadership}. "
            "Треки с n < {min_track} скрыты; прочерк не означает ноль. "
            "[Методика и полная таблица]({page})."
        ),
        "about": "О проекте",
        "about_items": [
            (
                "[Методика]({methodology}): что считается источником, как написаны вопросы и что "
                "означают метки."
            ),
            "[Источники и атрибуция]({sources}): каждая страница с датой проверки.",
            "[Атрибуция]({attribution}): исходные материалы, переработка и лицензии.",
            (
                "[Как участвовать](CONTRIBUTING.ru.md): добавить вопрос с датированным публичным "
                "источником."
            ),
            (
                "Лицензия Apache-2.0 · © 2026 ai-interview-atlas contributors. Пересказанный "
                "материал из лицензированных подборок указан на странице источников."
            ),
        ],
        "back": "← [AI Interview Atlas]({readme})",
        "asked_at": "Где спрашивали",
        "tests": "Что проверяет",
        "covers": "Сильный ответ покрывает",
        "read": "Читать",
        "generated": "сгенерировано по темам вакансий",
        "both": "Оба трека",
        "roles": "Роли",
        "loop": "Этапы интервью",
        "stage": "Этап",
        "what": "Что происходит",
        "basis": "Основание",
        "prep": "Официальные материалы для подготовки",
        "reported": "Вопросы, о которых сообщали для {company}",
        "none_reported": "Вопросов по этой компании пока нет.",
        "last_reviewed": "Этапы проверены {date}",
        "stale": "⚠️ старше года",
        "radar_title": "Радар требований",
        "period": "Период",
        "sample": "Выборка",
        "sample_value": (
            "{postings} вакансий: инженерия — {engineering}, лидерство — {leadership}"
        ),
        "market_value": "рынки: международный — {intl}, Россия — {ru}, не указан — {unknown}",
        "method": "Методика",
        "criteria": "Что засчитывается в каждой теме",
        "suppressed": (
            "Прочерк: тему упоминают меньше {min_cell} вакансий или в треке меньше {min_track} "
            "вакансий; такие ячейки не публикуются."
        ),
        "share": "{share}% ({postings})",
        "sources_title": "Источники и атрибуция",
        "retrieved": "проверено",
        "published": "опубликовано",
        "license": "лицензия",
        "attribution": (
            "Вопросы с меткой †, взятые из {title} ({publisher}), пересказаны своими словами "
            "со ссылкой на источник; подборка распространяется по лицензии {license}."
        ),
        "svg_title": "Доля вакансий, где упоминается тема",
        "ai_share": (
            "Вакансии трека «{track}» в выборке: сама роль связана с AI или машинным "
            "обучением в {share}% ({count} из {total})."
        ),
        "sample_names": {"engineering": "инженерия", "leadership": "лидерство"},
        "types": {
            "knowledge": "Знания",
            "coding": "Кодинг",
            "system_design": "System design",
            "product_case": "Продуктовый кейс",
            "applied_scenario": "Прикладной сценарий",
            "leadership": "Руководство",
            "behavioral": "Поведенческий",
            "self_presentation": "Самопрезентация",
        },
        "levels": {"mid": "Middle", "senior": "Senior", "staff": "Staff+", "director": "Director+"},
        "segments": {
            "frontier-lab": "Лаборатории frontier-AI",
            "big-tech": "Бигтех",
            "ai-infra": "AI-инфраструктура",
            "ai-native": "AI-native продукты",
            "enterprise-ai": "Корпоративный и forward-deployed AI",
            "fintech": "Финтех и платежи",
            "ru-big-tech": "Бигтех России",
        },
        "market_names": {"intl": "Международный", "ru": "Россия"},
        "claims": {
            "confirmed": "✅ подтверждено компанией",
            "participant_report": "🗣 отчёт кандидата",
            "secondary": "† гайд или подборка",
            "assumption": "❔ предположение",
        },
        "coding_values": {
            "required": "обязателен",
            "not_required": "не требуется",
            "varies": "зависит от роли",
            "unknown": "неизвестно",
        },
        "kinds": {
            "official": "Источники компаний",
            "participant_report": "Отчёты кандидатов",
            "prep_guide": "Гайды по подготовке",
            "secondary_compilation": "Подборки",
            "reference": "Справочные материалы",
        },
    },
}


def readme(lang: str) -> str:
    return "README.md" if lang == "en" else "README.ru.md"


def base(lang: str) -> str:
    return "docs" if lang == "en" else "docs/ru"


def theme_page(lang: str, theme: str) -> str:
    return f"{base(lang)}/themes/{theme}.md"


def company_page(lang: str, company: str) -> str:
    return f"{base(lang)}/companies/{company}.md"


def answers_page(lang: str, track: str) -> str:
    return f"{base(lang)}/answers/{track}.md"


def radar_page(lang: str) -> str:
    return f"{base(lang)}/radar.md"


def sources_page(lang: str) -> str:
    return f"{base(lang)}/sources.md"


def methodology_page(lang: str) -> str:
    return f"{base(lang)}/METHODOLOGY.md"


def svg_file(lang: str) -> str:
    return f"docs/assets/radar.{lang}.svg"


def other(lang: str) -> str:
    return "ru" if lang == "en" else "en"


def rel(page: str, target: str) -> str:
    return posixpath.relpath(target, posixpath.dirname(page) or ".")


def md(text: str) -> str:
    return text.replace("<", "&lt;").replace(">", "&gt;").strip()


def cell(text: str) -> str:
    return md(text).replace("|", "\\|").replace("\n", " ")


def percent(part: int, whole: int) -> int:
    return round(100 * part / whole) if whole else 0


class Renderer:
    def __init__(self, content: Content):
        self.content = content
        self.theme_order = {t["id"]: i for i, t in enumerate(content.taxonomy["themes"])}
        self.track_names = {t["id"]: t["name"] for t in content.taxonomy["tracks"]}

    def pages(self) -> dict[str, str]:
        pages: dict[str, str] = {}
        for lang in LANGS:
            pages[readme(lang)] = self.readme(lang)
            for theme in self.content.taxonomy["themes"]:
                pages[theme_page(lang, theme["id"])] = self.theme(lang, theme)
            for company in self.content.companies.values():
                pages[company_page(lang, company["id"])] = self.company(lang, company)
            for track in TRACKS:
                if self.answered(lang, track):
                    pages[answers_page(lang, track)] = self.answers(lang, track)
            pages[sources_page(lang)] = self.sources(lang)
            if self.content.radar:
                pages[radar_page(lang)] = self.radar(lang)
                pages[svg_file(lang)] = self.svg(lang)
        return {path: text.rstrip("\n") + "\n" for path, text in sorted(pages.items())}

    # Shared pieces

    def switch(self, lang: str, page: str, counterpart: str) -> str:
        return LABELS[lang]["switch"].format(other=rel(page, counterpart))

    def company_name(self, company: str, lang: str) -> str:
        return self.content.companies[company]["name"][lang]

    def asked_at(self, question: dict, lang: str, page: str) -> str:
        found = self.content.asked_at(question)
        ordered = sorted(
            found.items(), key=lambda item: (STRENGTH[item[1]], self.company_name(item[0], lang))
        )
        return ", ".join(
            f"[{self.company_name(company, lang)}]({rel(page, company_page(lang, company))})"
            f" {MARKERS[kind]}"
            for company, kind in ordered
        )

    def question(
        self, question: dict, lang: str, page: str, *, full: bool = True, theme_link: bool = False
    ) -> list[str]:
        labels = LABELS[lang]
        meta = [labels["types"][question["type"]]]
        if question.get("level"):
            meta.append(labels["levels"][question["level"]])
        if theme_link:
            theme = self.content.themes[question["theme"]]
            meta.append(f"[{theme['name'][lang]}]({rel(page, theme_page(lang, theme['id']))})")
        asked = self.asked_at(question, lang, page)
        if asked:
            meta.append(f"{labels['asked_at']}: {asked}")
        if question["provenance"] == "generated":
            meta.append(f"🧪 {labels['generated']}")
        lines = [f"- **{md(question['text'][lang])}**", f"  - {' · '.join(meta)}"]
        if not full:
            return lines
        lines.append(f"  - {labels['tests']}: {md(question['tests'][lang])}")
        if question.get("outline"):
            lines.append(f"  - {labels['covers']}:")
            lines += [f"    - {md(point)}" for point in question["outline"][lang]]
        if question.get("reading"):
            links = []
            for source_id in question["reading"]:
                source = self.content.sources[source_id]
                links.append(f"[{cell(source['title'])}]({source['url']}) ({source['publisher']})")
            lines.append(f"  - {labels['read']}: " + " · ".join(links))
        return lines

    def reviewed(self, company: dict, lang: str) -> str:
        """Review date, flagged when a year older than the newest content (not today's date)."""
        newest = date.fromisoformat(self.updated())
        stale = date.fromisoformat(company["reviewed"]) < newest - timedelta(days=365)
        return company["reviewed"] + (f" {LABELS[lang]['stale']}" if stale else "")

    def updated(self) -> str:
        content = self.content
        dates = [q["added"] for q in content.questions]
        dates += [c["reviewed"] for c in content.companies.values()]
        dates += [s["retrieved"] for s in content.sources.values()]
        return max(dates) if dates else ""

    def start_here(self, track: str) -> list[dict]:
        chosen = [q for q in self.content.questions if track in q.get("start_here", [])]
        return sorted(chosen, key=lambda q: (q.get("priority", 999), self.theme_order[q["theme"]]))

    def answered(self, lang: str, track: str) -> list[dict]:
        """Priority questions of this track that already have an answer in this language."""
        return [q for q in self.start_here(track) if q.get("answer", {}).get(lang)]

    # Pages

    def answers(self, lang: str, track: str) -> str:
        labels, page = LABELS[lang], answers_page(lang, track)
        name = self.track_names[track][lang]
        chosen, all_priority = self.answered(lang, track), self.start_here(track)
        back = labels["back"].format(readme=rel(page, readme(lang)))
        # The other language has its own page only once it has answers of its own.
        counterpart = answers_page(other(lang), track)
        header = (
            self.switch(lang, page, counterpart) + " · " + back
            if self.answered(other(lang), track)
            else back
        )
        lines = [
            HEADER,
            f"# {labels['answers'].format(track=name)}",
            "",
            header,
            "",
            md(labels["answers_intro"]),
            "",
            labels["answers_progress"].format(done=len(chosen), total=len(all_priority)),
        ]
        numbers = {q["id"]: number for number, q in enumerate(all_priority, 1)}
        for question in chosen:
            theme = self.content.themes[question["theme"]]
            link = rel(page, theme_page(lang, theme["id"]))
            lines += [
                "",
                f"### {numbers[question['id']]}. {md(question['text'][lang])}",
                "",
                f"*{labels['types'][question['type']]} · [{md(theme['name'][lang])}]({link})*",
                "",
                md(question["answer"][lang]),
            ]
            if question.get("reading"):
                links = []
                for source_id in question["reading"]:
                    source = self.content.sources[source_id]
                    links.append(f"[{cell(source['title'])}]({source['url']})")
                lines += ["", f"{labels['read']}: " + " · ".join(links)]
        return "\n".join(lines)

    def readme(self, lang: str) -> str:
        labels, content, page = LABELS[lang], self.content, readme(lang)
        counts = {track: sum(track in q["tracks"] for q in content.questions) for track in TRACKS}
        lines = [
            HEADER,
            "# AI Interview Atlas",
            "",
            self.switch(lang, page, readme(other(lang))),
            "",
            labels["tagline"],
            "",
            "**"
            + labels["stats"].format(
                questions=len(content.questions),
                companies=len(content.companies),
                sources=len(content.sources),
                updated=self.updated(),
                **counts,
            )
            + "**",
            "",
            f"## {labels['how']}",
            "",
        ]
        names = {track: self.track_names[track][lang] for track in TRACKS}
        items = labels["how_items"] if content.radar else labels["how_items_no_radar"]
        for index, item in enumerate(items, 1):
            lines.append(f"{index}. " + item.format(radar=radar_page(lang), **names))
        lines += ["", labels["legend"], "", f"## {labels['tracks']}", ""]
        for track in content.taxonomy["tracks"]:
            roles = [
                r["name"][lang] for r in content.taxonomy["roles"] if r["track"] == track["id"]
            ]
            lines.append(f"- **{track['name'][lang]}.** {md(track['summary'][lang])}")
            lines.append(f"  - {', '.join(roles)}")
        for track in TRACKS:
            chosen = self.start_here(track)
            if not chosen:
                continue
            lines += ["", f"## {labels['start'].format(track=names[track])}", ""]
            if self.answered(lang, track):
                link = rel(page, answers_page(lang, track))
                lines += [labels["answers_link"].format(page=link), ""]
            for question in chosen:
                lines += self.question(question, lang, page, full=False, theme_link=True)
        common = [q for q in content.questions if len(content.asked_at(q)) >= 2]
        if common:
            lines += ["", f"## {labels['common']}", "", labels["common_intro"]]
            for theme in content.taxonomy["themes"]:
                chosen = [q for q in common if q["theme"] == theme["id"]]
                if chosen:
                    link = rel(page, theme_page(lang, theme["id"]))
                    lines += ["", f"### [{theme['name'][lang]}]({link})", ""]
                    for question in chosen:
                        lines += self.question(question, lang, page, full=False)
        lines += [
            "",
            f"## {labels['themes']}",
            "",
            f"| {labels['theme']} | {names['engineering']} | {names['leadership']} |",
            "| --- | ---: | ---: |",
        ]
        for theme in content.taxonomy["themes"]:
            in_theme = [q for q in content.questions if q["theme"] == theme["id"]]
            per_track = [sum(track in q["tracks"] for q in in_theme) for track in TRACKS]
            link = rel(page, theme_page(lang, theme["id"]))
            lines.append(
                f"| [{cell(theme['name'][lang])}]({link}) | {per_track[0]} | {per_track[1]} |"
            )
        if content.companies:
            lines += [
                "",
                f"## {labels['companies']}",
                "",
                (
                    f"| {labels['company']} | {labels['segment']} | {labels['markets']} "
                    f"| {labels['coding']} | {labels['questions']} | {labels['reviewed']} |"
                ),
                "| --- | --- | --- | --- | ---: | --- |",
            ]
            for company in self.companies_in_order(lang):
                asked = sum(company["id"] in content.asked_at(q) for q in content.questions)
                markets = ", ".join(labels["market_names"][m] for m in company["markets"])
                link = rel(page, company_page(lang, company["id"]))
                lines.append(
                    f"| [{cell(company['name'][lang])}]({link}) "
                    f"| {labels['segments'][company['segment']]} | {markets} "
                    f"| {labels['coding_values'][company['coding']['value']]} | {asked} "
                    f"| {self.reviewed(company, lang)} |"
                )
        if content.radar:
            radar = content.radar
            lines += [
                "",
                f"## {labels['radar']}",
                "",
                labels["radar_intro"].format(
                    postings=radar["sample"]["postings"],
                    engineering=radar["sample"]["tracks"].get("engineering", 0),
                    leadership=radar["sample"]["tracks"].get("leadership", 0),
                    min_track=radar["min_track"],
                    start=radar["period"]["from"],
                    end=radar["period"]["to"],
                    page=radar_page(lang),
                ),
                *[f"{line}" for line in self.ai_share(lang)],
                "",
                f"![{labels['svg_title']}]({svg_file(lang)})",
            ]
        lines += ["", f"## {labels['about']}", ""]
        for item in labels["about_items"]:
            lines.append(
                "- "
                + item.format(
                    methodology=methodology_page(lang),
                    sources=sources_page(lang),
                    attribution=f"{base(lang)}/ATTRIBUTION.md",
                )
            )
        return "\n".join(lines)

    def companies_in_order(self, lang: str) -> list[dict]:
        return sorted(
            self.content.companies.values(),
            key=lambda c: (SEGMENTS.index(c["segment"]), c["name"][lang].casefold()),
        )

    def theme(self, lang: str, theme: dict) -> str:
        labels, page = LABELS[lang], theme_page(lang, theme["id"])
        questions = [q for q in self.content.questions if q["theme"] == theme["id"]]
        lines = [
            HEADER,
            f"# {theme['name'][lang]}",
            "",
            self.switch(lang, page, theme_page(other(lang), theme["id"]))
            + " · "
            + labels["back"].format(readme=rel(page, readme(lang))),
            "",
            md(theme["summary"][lang]),
        ]
        groups = [
            (labels["both"], lambda q: set(q["tracks"]) == set(TRACKS)),
            (self.track_names["engineering"][lang], lambda q: q["tracks"] == ["engineering"]),
            (self.track_names["leadership"][lang], lambda q: q["tracks"] == ["leadership"]),
        ]
        for title, belongs in groups:
            chosen = [q for q in questions if belongs(q)]
            if chosen:
                lines += ["", f"## {title}", ""]
                for question in chosen:
                    lines += self.question(question, lang, page)
        return "\n".join(lines)

    def company(self, lang: str, company: dict) -> str:
        labels, content = LABELS[lang], self.content
        page = company_page(lang, company["id"])
        name = company["name"][lang]
        markets = ", ".join(labels["market_names"][m] for m in company["markets"])
        lines = [
            HEADER,
            f"# {name}",
            "",
            self.switch(lang, page, company_page(other(lang), company["id"]))
            + " · "
            + labels["back"].format(readme=rel(page, readme(lang))),
            "",
            f"{labels['segments'][company['segment']]} · {markets} · "
            + labels["last_reviewed"].format(date=self.reviewed(company, lang)),
        ]
        if company.get("summary"):
            lines += ["", md(company["summary"][lang])]
        lines += ["", f"## {labels['roles']}", ""]
        for track in TRACKS:
            roles = [content.roles[r]["name"][lang] for r in company["roles"].get(track, [])]
            if roles:
                lines.append(f"- **{self.track_names[track][lang]}:** {', '.join(roles)}")
        lines += [
            "",
            f"## {labels['loop']}",
            "",
            f"| {labels['stage']} | {labels['what']} | {labels['basis']} |",
            "| --- | --- | --- |",
        ]
        for stage in company["loop"]:
            basis = [labels["claims"][stage["claim"]]]
            basis += [self.source_link(s, lang) for s in stage.get("sources", [])]
            detail = cell(stage["detail"][lang]) if stage.get("detail") else ""
            lines.append(f"| {cell(stage['stage'][lang])} | {detail} | {'<br>'.join(basis)} |")
        coding = company["coding"]
        coding_line = f"**{labels['coding']}:** {labels['coding_values'][coding['value']]}"
        if coding.get("note"):
            coding_line += f". {md(coding['note'][lang])}"
        if coding.get("sources"):
            coding_line += (
                " (" + ", ".join(self.source_link(s, lang) for s in coding["sources"]) + ")"
            )
        lines += ["", coding_line]
        if company.get("prep"):
            lines += ["", f"## {labels['prep']}", ""]
            lines += [f"- {self.source_link(s, lang)}" for s in company["prep"]]
        reported = [q for q in content.questions if company["id"] in content.asked_at(q)]
        lines += ["", f"## {labels['reported'].format(company=name)}"]
        if not reported:
            lines += ["", labels["none_reported"]]
        for theme in content.taxonomy["themes"]:
            chosen = [q for q in reported if q["theme"] == theme["id"]]
            if chosen:
                link = rel(page, theme_page(lang, theme["id"]))
                lines += ["", f"### [{theme['name'][lang]}]({link})", ""]
                for question in chosen:
                    lines += self.question(question, lang, page)
        return "\n".join(lines)

    def source_link(self, source_id: str, lang: str) -> str:
        source, labels = self.content.sources[source_id], LABELS[lang]
        parts = [f"[{cell(source['title'])}]({source['url']})", cell(source["publisher"])]
        if source.get("published"):
            parts.append(f"{labels['published']} {source['published']}")
        parts.append(f"{labels['retrieved']} {source['retrieved']}")
        return ", ".join(parts)

    def sources(self, lang: str) -> str:
        labels, page = LABELS[lang], sources_page(lang)
        lines = [
            HEADER,
            f"# {labels['sources_title']}",
            "",
            self.switch(lang, page, sources_page(other(lang)))
            + " · "
            + labels["back"].format(readme=rel(page, readme(lang))),
        ]
        by_kind = {kind: [] for kind in SOURCE_KINDS}
        for source in self.content.sources.values():
            by_kind[source["kind"]].append(source)
        licensed = sorted(
            (s for s in by_kind["secondary_compilation"] if s.get("license")),
            key=lambda s: s["id"],
        )
        if licensed:
            lines.append("")
            for source in licensed:
                lines.append(
                    labels["attribution"].format(
                        title=f"[{cell(source['title'])}]({source['url']})",
                        publisher=cell(source["publisher"]),
                        license=source["license"],
                    )
                )
        for kind in SOURCE_KINDS:
            chosen = sorted(
                by_kind[kind], key=lambda s: (s["publisher"].casefold(), s["title"].casefold())
            )
            if not chosen:
                continue
            lines += ["", f"## {labels['kinds'][kind]}", ""]
            for source in chosen:
                parts = [f"[{cell(source['title'])}]({source['url']})", cell(source["publisher"])]
                if source.get("published"):
                    parts.append(f"{labels['published']} {source['published']}")
                parts.append(f"{labels['retrieved']} {source['retrieved']}")
                if source.get("license"):
                    parts.append(f"{labels['license']} {source['license']}")
                line = "- " + " · ".join(parts)
                if source.get("note"):
                    line += f". {md(source['note'][lang])}"
                lines.append(line)
        return "\n".join(lines)

    def ai_share(self, lang: str) -> list[str]:
        radar, lines = self.content.radar, []
        for track in TRACKS:
            count = radar.get("ai_mentions", {}).get(track)
            if count:
                total = radar["sample"]["tracks"][track]
                lines.append(
                    LABELS[lang]["ai_share"].format(
                        share=percent(count, total),
                        track=LABELS[lang]["sample_names"][track],
                        count=count,
                        total=total,
                    )
                )
        return lines

    def radar_cells(self) -> list[tuple[dict, dict[str, dict | None]]]:
        radar = self.content.radar
        rows = {(row["track"], row["theme"]): row for row in radar["rows"]}
        result = []
        for theme in self.content.taxonomy["themes"]:
            cells = {track: rows.get((track, theme["id"])) for track in TRACKS}
            if any(cells.values()):
                result.append((theme, cells))
        return result

    def radar(self, lang: str) -> str:
        labels, radar, page = LABELS[lang], self.content.radar, radar_page(lang)
        sample = radar["sample"]
        names = {track: self.track_names[track][lang] for track in TRACKS}
        lines = [
            HEADER,
            f"# {labels['radar_title']}",
            "",
            self.switch(lang, page, radar_page(other(lang)))
            + " · "
            + labels["back"].format(readme=rel(page, readme(lang))),
            "",
            f"- **{labels['period']}:** {radar['period']['from']} — {radar['period']['to']}",
            f"- **{labels['sample']}:** "
            + labels["sample_value"].format(
                postings=sample["postings"],
                engineering=sample["tracks"].get("engineering", 0),
                leadership=sample["tracks"].get("leadership", 0),
            )
            + "; "
            + labels["market_value"].format(
                intl=sample["markets"].get("intl", 0),
                ru=sample["markets"].get("ru", 0),
                unknown=sample["markets"].get("unknown", 0),
            ),
            "",
            f"![{labels['svg_title']}]({rel(page, svg_file(lang))})",
            "",
            f"| {labels['theme']} | {names['engineering']} | {names['leadership']} |",
            "| --- | ---: | ---: |",
        ]
        for theme, cells in self.radar_cells():
            values = []
            for track in TRACKS:
                row = cells[track]
                total = sample["tracks"].get(track, 0)
                values.append(
                    labels["share"].format(
                        share=percent(row["postings"], total), postings=row["postings"]
                    )
                    if row
                    else "—"
                )
            link = rel(page, theme_page(lang, theme["id"]))
            lines.append(f"| [{cell(theme['name'][lang])}]({link}) | {values[0]} | {values[1]} |")
        lines += ["", *self.ai_share(lang)] if self.ai_share(lang) else []
        lines += [
            "",
            labels["suppressed"].format(min_cell=radar["min_cell"], min_track=radar["min_track"]),
            "",
            f"## {labels['method']}",
            "",
            md(radar["method"][lang]),
        ]
        if radar.get("criteria"):
            lines += ["", f"### {labels['criteria']}", ""]
            for theme in self.content.taxonomy["themes"]:
                criterion = radar["criteria"].get(theme["id"])
                if criterion:
                    lines.append(f"- **{theme['name'][lang]}:** {md(criterion[lang])}")
        return "\n".join(lines)

    def svg(self, lang: str) -> str:
        labels, sample = LABELS[lang], self.content.radar["sample"]
        cells = self.radar_cells()
        label_width, bar_width, row_height, top = 300, 380, 34, 70
        width = label_width + bar_width + 80
        height = top + row_height * len(cells) + 90
        font = 'font-family="Segoe UI, Helvetica, Arial, sans-serif"'
        parts = [
            (
                f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" '
                f'viewBox="0 0 {width} {height}" role="img" '
                f'aria-label="{escape(labels["svg_title"], {chr(34): "&quot;"})}">'
            ),
            f"<title>{escape(labels['svg_title'])}</title>",
            (
                f'<rect x="0.5" y="0.5" width="{width - 1}" height="{height - 1}" rx="8" '
                'fill="#f6f8fa" stroke="#d0d7de"/>'
            ),
            (
                f'<text x="16" y="28" {font} font-size="16" font-weight="600" fill="#1f2328">'
                f"{escape(labels['svg_title'])}</text>"
            ),
        ]
        x = 16
        for track in TRACKS:
            name = escape(self.track_names[track][lang])
            parts.append(f'<rect x="{x}" y="42" width="12" height="12" fill="{COLORS[track]}"/>')
            parts.append(
                f'<text x="{x + 18}" y="53" {font} font-size="13" fill="#1f2328">{name}</text>'
            )
            x += 200
        for index, (theme, row_cells) in enumerate(cells):
            y = top + index * row_height
            parts.append(
                f'<text x="{label_width - 10}" y="{y + 17}" {font} font-size="13" '
                f'text-anchor="end" fill="#1f2328">{escape(theme["name"][lang])}</text>'
            )
            for offset, track in enumerate(TRACKS):
                row = row_cells[track]
                bar_y = y + 4 + offset * 13
                if not row:
                    parts.append(
                        f'<text x="{label_width}" y="{bar_y + 10}" {font} font-size="11" '
                        'fill="#59636e">—</text>'
                    )
                    continue
                share = percent(row["postings"], sample["tracks"].get(track, 0))
                length = max(1, round(bar_width * share / 100))
                parts.append(
                    f'<rect x="{label_width}" y="{bar_y}" width="{length}" height="11" '
                    f'fill="{COLORS[track]}"/>'
                )
                parts.append(
                    f'<text x="{label_width + length + 6}" y="{bar_y + 10}" {font} '
                    f'font-size="11" fill="#1f2328">{share}%</text>'
                )
        radar = self.content.radar
        denominators = "; ".join(
            f"{labels['sample_names'][track]} n={sample['tracks'].get(track, 0)}"
            for track in TRACKS
        )
        footer = [
            denominators,
            (
                f"— = suppressed, not zero (track n < {radar['min_track']} or theme n < {radar['min_cell']})."
                if lang == "en"
                else f"— = скрыто, не ноль (трек n < {radar['min_track']} или тема n < {radar['min_cell']})."
            ),
            f"{radar['period']['from']} — {radar['period']['to']}",
        ]
        for index, line in enumerate(footer):
            y = top + row_height * len(cells) + 22 + index * 20
            parts.append(
                f'<text x="16" y="{y}" {font} font-size="12" fill="#59636e">{escape(line)}</text>'
            )
        parts.append("</svg>")
        return "\n".join(parts)


def render(content: Content) -> dict[str, str]:
    """Every generated file, keyed by its path relative to the repository root."""
    return Renderer(content).pages()
