"""Render bilingual Markdown pages and a static SVG from validated content, deterministically."""

from __future__ import annotations

import posixpath
from collections import Counter
from datetime import date, timedelta
from urllib.parse import quote
from xml.sax.saxutils import escape

from .content import ROLE_LINK, STRENGTH, TRACKS, Content

LANGS = ("en", "ru")
HEADER = "<!-- Generated by scripts/build.py from src/content. Edit the YAML, not this file. -->"
RELEASES = "https://github.com/eiler2005/ai-interview-atlas/releases/latest"
BANNER = (
    "https://github.com/eiler2005/ai-interview-atlas/releases/download/v0.1.1/hero-banner-v2.png"
)
REPO = "https://github.com/eiler2005/ai-interview-atlas"
BADGES = (
    "[![License: Apache-2.0](https://img.shields.io/badge/license-Apache--2.0-blue.svg)]"
    "(LICENSE)\n"
    f"[![checks]({REPO}/actions/workflows/checks.yml/badge.svg)]"
    f"({REPO}/actions/workflows/checks.yml)\n"
    f"[![PDF editions](https://img.shields.io/badge/PDF-editions-137c80)]({RELEASES})"
)
MARKERS = {
    "official": "✅",
    "participant_report": "🗣",
    "prep_guide": "†",
    "secondary_compilation": "†",
}
SEGMENTS = (
    "frontier-lab",
    "big-tech",
    "ai-infra",
    "ai-native",
    "enterprise-ai",
    "fintech",
    "ru-big-tech",
)
SOURCE_KINDS = (
    "official",
    "participant_report",
    "prep_guide",
    "secondary_compilation",
    "reference",
    "posting",
)
COLORS = {"engineering": "#1f6feb", "leadership": "#bc4c00"}
_GUIDE_PATHS = {
    "learning_roadmap": "LEARNING_ROADMAP.md",
    "ai_assisted_coding": "learning/AI_ASSISTED_CODING.md",
    "production_ai_engineering": "learning/PRODUCTION_AI_ENGINEERING.md",
    "ai_leadership": "learning/AI_LEADERSHIP.md",
    "coverage_audit": "research/ATLAS_COVERAGE_AUDIT.md",
    "engineering_research": "research/ENGINEERING_RESEARCH.md",
    "leadership_audit": "research/LEADERSHIP_AUDIT.md",
    "atlas_expansion": "plans/ATLAS_EXPANSION.md",
}


def ru_count(count: int, one: str, few: str, many: str) -> str:
    """Pick the Russian noun form a numeral governs: 1 вопрос, 2 вопроса, 5 вопросов."""
    if 11 <= count % 100 <= 14:
        return many
    last = count % 10
    if last == 1:
        return one
    if 2 <= last <= 4:
        return few
    return many


LABELS = {
    "en": {
        "switch": "English · [Русский]({other})",
        "stats": (
            "Questions: {questions} (engineering {engineering}, leadership {leadership}) · "
            "companies: {companies} · sources: {sources} · updated {updated}"
        ),
        "banner_alt": (
            "AI Interview Atlas — Engineering & Leadership. Questions, answers and learning paths."
        ),
        "hero": (
            "Prepare for AI interviews with attributed questions, practice prompts and primary "
            "reading."
        ),
        "intro": (
            "Two tracks — AI Engineering and AI Leadership — with company interview guides and "
            "answer checklists. Each reported question cites its evidence; the markers distinguish "
            "company confirmation, candidate reports and secondary compilations. Generated practice "
            "questions are labelled separately."
        ),
        "source_mix": (
            "Of {published} questions attributed to published sources, {secondary_only} rely only "
            "on preparation guides or compilations (†). Another {generated} are generated practice "
            "questions (🧪). Primary reading supports technical understanding; it does not prove "
            "that an employer asked a question."
        ),
        "source_concentration": (
            "{largest_source_questions} questions cite the same compilation: {largest_source_link}. "
            "This concentration limits independent corroboration; company tags from that "
            "compilation remain secondary evidence."
        ),
        "offline": (
            "Released PDF books are dated snapshots for offline reading. The website may contain "
            "newer questions and guides; check the release date before using a book as the current "
            "edition."
        ),
        "inside": "What is inside",
        "inside_items": [
            (
                "**{questions} questions** across {themes} themes: {engineering} for engineering, "
                "{leadership} for leadership. Each says what it tests and what a strong answer covers."
            ),
            (
                "**{answers} written answers** to the priority questions — a paragraph you could say "
                "aloud, not a link to a paid course."
            ),
            (
                "**{companies} company pages**: the interview loop stage by stage, the coding "
                "requirement, and the questions reported for that company."
            ),
            (
                "**{families} role pages** in the [AI roles guide]({roles_page}): what each role "
                "involves, how it is interviewed and which questions to practise."
            ),
            (
                "**{sources} sources**, each with the date it was read, so you can check anything "
                "yourself and see what has aged."
            ),
            (
                "**A requirements radar** built from real job postings: what employers actually ask "
                "for, by theme."
            ),
        ],
        "answers_pending": (
            "**Written answers** to the priority questions exist in Russian today; the English "
            "ones follow in the next wave."
        ),
        "different": "Why this one",
        "different_items": [
            (
                "**Every claim is dated and attributed.** A marker tells you whether the company "
                "confirmed it, a candidate reported it, or a guide repeated it without a source."
            ),
            (
                "**Leadership is covered properly.** Product, engineering management, direction and "
                "programme delivery are first-class here, not an afterthought behind the coding "
                "questions."
            ),
            (
                "**Nothing is sold.** Apache-2.0, no course, no sign-up. Where an answer needs "
                "outside reading, the link goes to the paper or the documentation."
            ),
        ],
        "quickstart": "Start in three steps",
        "learning_path": (
            "For a study sequence with weekly practice and completion checks, use the "
            "[learning path]({page})."
        ),
        "learning_routes": (
            "Choose a focused route from the [learning roadmap]({learning_roadmap}): "
            "[AI-assisted coding]({ai_assisted_coding}), "
            "[production AI engineering]({production_ai_engineering}) or "
            "[AI Leadership]({ai_leadership})."
        ),
        "learning_evidence": (
            "See the [coverage audit]({coverage_audit}), "
            "[Engineering research]({engineering_research}), "
            "[Leadership audit]({leadership_audit}) and [expansion plan]({atlas_expansion}) "
            "for evidence limits and next steps."
        ),
        "quickstart_items": [
            (
                "Pick your track and work through its priority questions: "
                "[{engineering_name}]({engineering_page}) · [{leadership_name}]({leadership_page})."
            ),
            (
                "Answer aloud before reading anything. Each question lists what it tests and what "
                "a strong answer covers; the priority ones add reading and a written answer."
            ),
            "Before an interview, open that employer's page and the themes its loop covers.",
        ],
        "how": "How to use it",
        "how_items": [
            (
                "Pick your track: **{engineering}** or **{leadership}**. The track pages below list "
                "the roles each one covers."
            ),
            (
                "Work through *Start here* for your track, then the themes where the "
                "[requirements radar]({radar}) shows the most demand."
            ),
            (
                "Before an interview, open the company page: loop stages with their basis, the "
                "coding requirement and the questions reported for that company."
            ),
            (
                "Practise aloud. Every question says what it tests and what a strong answer "
                "covers; priority questions also have reading and a written answer. Use those as "
                "prompts for reasoning, not scripts."
            ),
        ],
        "how_items_no_radar": [
            (
                "Pick your track: **{engineering}** or **{leadership}**. The track pages below list "
                "the roles each one covers."
            ),
            "Work through *Start here* for your track, then the themes you expect in your loop.",
            (
                "Before an interview, open the company page: loop stages with their basis, the "
                "coding requirement and the questions reported for that company."
            ),
            (
                "Practise aloud. Every question says what it tests and what a strong answer "
                "covers; priority questions also have reading and a written answer. Use those as "
                "prompts for reasoning, not scripts."
            ),
        ],
        "legend": (
            "Markers: ✅ confirmed by the company · 🗣 candidate report · † prep guide or "
            "compilation without a first-hand source · 🧪 generated from job-posting themes. "
            "Interview loops change often, so check the retrieval date."
        ),
        "tracks": "Tracks and roles",
        "start": "Start here: {track}",
        "answers": "Answers: {track}",
        "start_intro": (
            "The priority questions of this track, in study order. Answer each one aloud before "
            "you read anything: the theme page behind every question adds what a strong answer "
            "covers and what to read."
        ),
        "answers_intro": (
            "Written answers to the priority questions of this track, in the same order and "
            "numbering as *Start here*. Answer each question yourself first: what follows is one "
            "good answer, not the only correct one, and an interviewer is listening to your "
            "reasoning rather than checking your wording."
        ),
        "answers_progress": "Answers written: {done} of {total}.",
        "answers_link": "[Answers to these questions]({page})",
        "common": "Asked across companies",
        "common_intro": "Questions reported at two or more companies, strongest basis first.",
        "themes": "Themes",
        "theme": "Theme",
        "companies": "Companies",
        "company": "Company",
        "segment": "Segment",
        "markets": "Markets",
        "coding": "Coding",
        "questions": "Questions",
        "reviewed": "Reviewed",
        "radar": "What job postings ask for",
        "radar_intro": (
            "Sample: {postings} postings ({start} to {end}). Percentages use each track's "
            "denominator: engineering n={engineering}, leadership n={leadership}. "
            "Tracks below n={min_track} are suppressed; a dash does not mean zero. "
            "[Method and full table]({page})."
        ),
        "about": "About",
        "about_items": [
            (
                "[Methodology]({methodology}): what counts as a source, how questions are "
                "written and what the markers mean."
            ),
            "[Sources and attribution]({sources}): every cited page with its retrieval date.",
            "[Attribution]({attribution}): upstream material, adaptations and licensing.",
            "[Contributing](CONTRIBUTING.md): add a question with a dated public source.",
            "[Roadmap]({roadmap}): what comes next, and what this project will not do.",
            (
                "[Learning path]({learning_path}) — a study curriculum; the project roadmap "
                "describes repository development."
            ),
            (
                "License: Apache-2.0 · © 2026 ai-interview-atlas contributors. Paraphrased "
                "material from licensed compilations is attributed on the sources page."
            ),
        ],
        "back": "← [AI Interview Atlas]({readme})",
        "crumbs": "[AI Interview Atlas]({readme}) › [{section}]({hub})",
        "navigate": "**Navigate:**",
        "map": "Map of the atlas",
        "map_intro": (
            "Every page of the atlas in one place. Start with the priority questions of your "
            "track, then go deeper by theme or by employer."
        ),
        "start_short": "Start: {track}",
        "start_name": "Start here",
        "answers_name": "Answers",
        "start_summary": "{count} priority questions in study order",
        "answers_summary": "{done} of {total} written",
        "theme_summary": "What it covers",
        "reference": "Reference",
        "reference_items": [
            ("common", "Asked across companies", "questions reported at two or more companies"),
            ("radar", "Requirements radar", "what job postings ask for, by theme"),
            ("learning_path", "Learning path", "a study curriculum with weekly practice"),
            (
                "learning_roadmap",
                "Learning roadmap",
                "Choose a focused route alongside the existing eight-week baseline",
            ),
            (
                "ai_assisted_coding",
                "AI-assisted coding",
                "Four weeks of code reading, bounded AI assistance, testing and review",
            ),
            (
                "production_ai_engineering",
                "Production AI engineering",
                "Eight weeks of contracts, evaluation, retrieval, tools and operations",
            ),
            (
                "ai_leadership",
                "AI Leadership",
                "An eight-week route through decisions, evidence and delivery",
            ),
            (
                "coverage_audit",
                "Coverage audit",
                "Repository coverage, evidence limits and remaining gaps",
            ),
            (
                "engineering_research",
                "Engineering research",
                "Source comparison and the basis for two Engineering routes",
            ),
            (
                "leadership_audit",
                "Leadership audit",
                "Evidence and practice coverage for leadership responsibilities",
            ),
            (
                "atlas_expansion",
                "Expansion plan",
                "Priorities, dependencies and acceptance criteria for future work",
            ),
            (
                "reasoning_models",
                "Reasoning models",
                "compute budgets, evaluation and the limits of reasoning traces",
            ),
            (
                "ai_roles",
                "AI roles",
                "six role families: responsibilities, interviews, questions and preparation",
            ),
            ("methodology", "Methodology", "what counts as a source and what the markers mean"),
            ("sources", "Sources", "every cited page with its retrieval date"),
            ("attribution", "Attribution", "upstream material, adaptations and licensing"),
            ("roadmap", "Roadmap", "what comes next, and what this project will not do"),
            ("changelog", "Changelog", "what changed in each edition"),
            (
                "contributing",
                "Contributing",
                "report a problem or add a question with a dated public source",
            ),
            ("pdf", "PDF editions", "the same content as printable books"),
        ],
        "on_page": "On this page",
        "roles_title": "AI roles: responsibilities, interviews and preparation",
        "roles_checked": (
            "Job postings checked on {date}. They describe responsibilities, not how candidates "
            "are interviewed."
        ),
        "roles_overview": "Overview",
        "role_family": "Role family",
        "role_owns": "What it owns",
        "role_stages": "Reported stages",
        "role_companies": "Companies",
        "role_reported_count": "Reported questions",
        "role_practice_count": "Practice questions",
        "role_pages": "Role pages",
        "role_scope": "What the role involves",
        "role_sources": "Sources",
        "role_interviews": "How it is interviewed",
        "role_interviews_intro": (
            "Stages that sources report for these roles, taken from the company pages. Markers "
            "show the basis; interview loops change, so check the dates."
        ),
        "role_no_interviews": (
            "No public interview evidence for these roles is recorded yet. A job posting "
            "describes the work; it does not show how candidates are interviewed."
        ),
        "role_company_pages": "Company pages that cover these roles: {links}.",
        "role_reported": "Reported for these roles",
        "role_reported_intro": "Questions whose source says they were asked for one of these roles.",
        "role_practice": "Also practise",
        "role_practice_intro": "An editorial selection: relevant to the role, but not reported for it.",
        "role_no_questions": "No questions are linked to these roles yet.",
        "role_prep": "Preparation",
        "role_route": "Preparation route",
        "role_deliverable": "Practice deliverable",
        "checklist": "Checklist",
        "answer_link": "✍ [Answer]({page})",
        "fix": "Suggest a fix",
        "fix_title": "[Correction] {id}",
        "contents": "Contents",
        "to_contents": "[↑ Contents](#contents)",
        "asked_at": "Asked at",
        "tests": "Tests",
        "covers": "A strong answer covers",
        "read": "Read",
        "generated": "generated from job-posting themes",
        "both": "Both tracks",
        "roles": "Roles covered",
        "loop": "Interview loop",
        "stage": "Stage",
        "what": "What happens",
        "basis": "Basis",
        "prep": "Official preparation material",
        "reported": "Questions reported for {company}",
        "none_reported": "No company-specific questions are recorded yet.",
        "last_reviewed": "Loop reviewed {date}",
        "stale": "⚠️ older than a year",
        "radar_title": "Requirements radar",
        "period": "Period",
        "sample": "Sample",
        "sample_value": "{postings} postings: engineering {engineering}, leadership {leadership}",
        "market_value": "markets: international {intl}, Russia {ru}, unknown {unknown}",
        "method": "Method",
        "criteria": "What counts for each theme",
        "suppressed": (
            "A dash means fewer than {min_cell} postings mention the theme, or the track has "
            "fewer than {min_track} postings; such cells are not published."
        ),
        "share": "{share}% ({postings})",
        "sources_title": "Sources and attribution",
        "retrieved": "retrieved",
        "published": "published",
        "license": "license",
        "attribution": (
            "Questions marked † that come from {title} ({publisher}) are paraphrased and "
            "attributed to it; that compilation is licensed under {license}."
        ),
        "svg_title": "Share of postings that mention each theme",
        "ai_share": (
            "{track} postings in the sample: the role itself involves AI or machine "
            "learning in {share}% ({count} of {total})."
        ),
        "sample_names": {"engineering": "Engineering", "leadership": "Leadership"},
        "types": {
            "knowledge": "Knowledge",
            "coding": "Coding",
            "system_design": "System design",
            "product_case": "Product case",
            "applied_scenario": "Applied scenario",
            "leadership": "Leadership",
            "behavioral": "Behavioral",
            "self_presentation": "Self-presentation",
        },
        "levels": {"mid": "Mid", "senior": "Senior", "staff": "Staff+", "director": "Director+"},
        "segments": {
            "frontier-lab": "Frontier AI labs",
            "big-tech": "Big Tech",
            "ai-infra": "AI infrastructure",
            "ai-native": "AI-native products",
            "enterprise-ai": "Enterprise and forward-deployed AI",
            "fintech": "Fintech and payments",
            "ru-big-tech": "Russian Big Tech",
        },
        "market_names": {"intl": "International", "ru": "Russia"},
        "claims": {
            "confirmed": "✅ confirmed by the company",
            "participant_report": "🗣 candidate report",
            "secondary": "† prep guide or compilation",
            "assumption": "❔ assumption",
        },
        "coding_values": {
            "required": "required",
            "not_required": "not required",
            "varies": "varies by role",
            "unknown": "unknown",
        },
        "kinds": {
            "official": "Company sources",
            "participant_report": "Candidate reports",
            "prep_guide": "Preparation guides",
            "secondary_compilation": "Compilations",
            "reference": "Reference material",
            "posting": "Job postings (role scope only)",
        },
    },
    "ru": {
        "switch": "[English]({other}) · Русский",
        "stats": (
            "Вопросов: {questions} (инженерия — {engineering}, лидерство — {leadership}) · "
            "компаний: {companies} · источников: {sources} · обновлено {updated}"
        ),
        "banner_alt": (
            "AI Interview Atlas — AI-инженерия и AI-лидерство. Вопросы, ответы и учебные планы."
        ),
        "hero": (
            "Готовьтесь к AI-интервью: вопросы с указанием источников, учебные задачи и "
            "первоисточники для изучения."
        ),
        "intro": (
            "Два трека — AI Engineering и AI Leadership, процессы интервью в компаниях и планы "
            "ответов. У каждого вопроса из публикаций указано основание; метки различают "
            "подтверждение компании, отчёт кандидата и вторичную подборку. Сгенерированные учебные "
            "вопросы отмечены отдельно."
        ),
        "source_mix": (
            "Из {published} вопросов с опубликованными источниками {secondary_only} опираются "
            "только на подготовительные гайды или подборки (†). Ещё {generated} — сгенерированные "
            "учебные вопросы (🧪). Первоисточники для чтения помогают разобраться в теме, но не "
            "доказывают, что работодатель задавал вопрос."
        ),
        "source_concentration": (
            "Число вопросов, ссылающихся на одну подборку: {largest_source_questions} — "
            "{largest_source_link}. "
            "Это ограничивает независимое подтверждение; указания компаний из этой подборки "
            "остаются вторичными свидетельствами."
        ),
        "offline": (
            "Опубликованные PDF-книги — снимки атласа на дату выпуска для чтения офлайн. На сайте "
            "могут быть более новые вопросы и гайды; сверяйте дату релиза, прежде чем считать книгу "
            "текущей редакцией."
        ),
        "inside": "Что внутри",
        "inside_items": [
            (
                "**{questions} {questions_word}** в {themes} темах: {engineering} по инженерии, "
                "{leadership} по лидерству. У каждого указано, что он проверяет и что покрывает сильный ответ."
            ),
            (
                "**{answers} {answers_word}** на приоритетные вопросы — абзац, который можно "
                "произнести вслух, а не ссылка на платный курс."
            ),
            (
                "**{companies} {companies_word} компаний**: этапы интервью по шагам, требование "
                "к кодингу и вопросы, о которых сообщали для этой компании."
            ),
            (
                "**{families} {families_word} профессий** в [путеводителе]({roles_page}): чем "
                "занимается каждая AI-роль, как проходит собеседование и какие вопросы готовить."
            ),
            (
                "**{sources} {sources_word}**, у каждого дата прочтения: любое утверждение можно "
                "проверить самому и увидеть, что устарело."
            ),
            (
                "**Радар требований** по реальным вакансиям: что работодатели просят на самом деле, "
                "в разрезе тем."
            ),
        ],
        "answers_pending": (
            "**Написанные ответы** на приоритетные вопросы пока есть на русском; английские "
            "появятся следующей волной."
        ),
        "different": "Чем этот отличается",
        "different_items": [
            (
                "**У каждого утверждения есть дата и источник.** Метка показывает, подтвердила ли "
                "это компания, рассказал кандидат или гайд повторил без первоисточника."
            ),
            (
                "**Лидерство разобрано всерьёз.** Продукт, управление инженерами, директорские роли "
                "и руководство программами здесь равноправны, а не приложение к задачам на код."
            ),
            (
                "**Ничего не продаётся.** Apache-2.0, без курса и регистрации. Где ответу нужно "
                "внешнее чтение, ссылка ведёт на статью или документацию."
            ),
        ],
        "quickstart": "Как начать за три шага",
        "learning_path": (
            "Порядок изучения, еженедельная практика и критерии готовности — в "
            "[учебном плане]({page})."
        ),
        "learning_routes": (
            "Выберите предметный маршрут по [карте обучения]({learning_roadmap}): "
            "[AI-ассистированный кодинг]({ai_assisted_coding}), "
            "[прикладная AI-инженерия]({production_ai_engineering}) или "
            "[AI Leadership]({ai_leadership})."
        ),
        "learning_evidence": (
            "Границы свидетельств и следующие шаги описаны в "
            "[аудите покрытия]({coverage_audit}), "
            "[исследовании Engineering]({engineering_research}), "
            "[аудите Leadership]({leadership_audit}) и [плане расширения]({atlas_expansion})."
        ),
        "quickstart_items": [
            (
                "Выберите трек и пройдите его приоритетные вопросы: "
                "[{engineering_name}]({engineering_page}) · [{leadership_name}]({leadership_page})."
            ),
            (
                "Сначала отвечайте вслух и только потом читайте. У каждого вопроса написано, что он "
                "проверяет и что покрывает сильный ответ; у приоритетных есть ещё материалы для "
                "чтения и написанный ответ."
            ),
            "Перед интервью откройте страницу работодателя и темы, которые есть в его цикле.",
        ],
        "how": "Как пользоваться",
        "how_items": [
            (
                "Выберите трек: **{engineering}** или **{leadership}**. Ниже перечислены роли "
                "каждого трека."
            ),
            (
                "Пройдите раздел «С чего начать» своего трека, затем темы, которые чаще всего "
                "требуют вакансии по [радару требований]({radar})."
            ),
            (
                "Перед интервью откройте страницу компании: этапы с основаниями, требование к "
                "кодингу и вопросы, о которых сообщали для этой компании."
            ),
            (
                "Отвечайте вслух. Каждый вопрос объясняет, что проверяет и что покрывает сильный "
                "ответ; у приоритетных есть ещё чтение и написанный ответ. Используйте их для "
                "рассуждений, а не заучивания."
            ),
        ],
        "how_items_no_radar": [
            (
                "Выберите трек: **{engineering}** или **{leadership}**. Ниже перечислены роли "
                "каждого трека."
            ),
            "Пройдите раздел «С чего начать» своего трека, затем темы, которые ждёте на интервью.",
            (
                "Перед интервью откройте страницу компании: этапы с основаниями, требование к "
                "кодингу и вопросы, о которых сообщали для этой компании."
            ),
            (
                "Отвечайте вслух. Каждый вопрос объясняет, что проверяет и что покрывает сильный "
                "ответ; у приоритетных есть ещё чтение и написанный ответ. Используйте их для "
                "рассуждений, а не заучивания."
            ),
        ],
        "legend": (
            "Метки: ✅ подтверждено компанией · 🗣 отчёт кандидата · † гайд или подборка без "
            "первоисточника · 🧪 сгенерировано по темам вакансий. Этапы интервью часто "
            "меняются — смотрите дату проверки."
        ),
        "tracks": "Треки и роли",
        "start": "С чего начать: {track}",
        "answers": "Ответы: {track}",
        "start_intro": (
            "Приоритетные вопросы трека в порядке изучения. Сначала ответьте вслух и только "
            "потом читайте: на странице темы у каждого вопроса есть чек-лист ответа и материалы "
            "для чтения."
        ),
        "answers_intro": (
            "Письменные ответы на приоритетные вопросы трека в том же порядке и нумерации, что и "
            "в разделе «С чего начать». Сначала ответьте сами: здесь один из хороших ответов, а "
            "не единственно верный, и интервьюер слушает ваши рассуждения, а не совпадение "
            "формулировок."
        ),
        "answers_progress": "Ответы готовы: {done} из {total}.",
        "answers_link": "[Ответы на эти вопросы]({page})",
        "common": "Спрашивают в нескольких компаниях",
        "common_intro": "Вопросы, о которых сообщали в двух и более компаниях; сильное основание — первым.",
        "themes": "Темы",
        "theme": "Тема",
        "companies": "Компании",
        "company": "Компания",
        "segment": "Сегмент",
        "markets": "Рынки",
        "coding": "Кодинг",
        "questions": "Вопросы",
        "reviewed": "Проверено",
        "radar": "Что требуют вакансии",
        "radar_intro": (
            "Выборка: {postings} вакансий ({start} — {end}). Проценты рассчитаны внутри "
            "каждого трека: инженерия n={engineering}, лидерство n={leadership}. "
            "Треки с n < {min_track} скрыты; прочерк не означает ноль. "
            "[Методика и полная таблица]({page})."
        ),
        "about": "О проекте",
        "about_items": [
            (
                "[Методика]({methodology}): что считается источником, как написаны вопросы и что "
                "означают метки."
            ),
            "[Источники и атрибуция]({sources}): каждая страница с датой проверки.",
            "[Атрибуция]({attribution}): исходные материалы, переработка и лицензии.",
            (
                "[Как участвовать](CONTRIBUTING.ru.md): добавить вопрос с датированным публичным "
                "источником."
            ),
            ("[Дорожная карта]({roadmap}): что будет дальше и чего проект делать не будет."),
            (
                "[Учебный план]({learning_path}) — программа подготовки; дорожная карта "
                "проекта описывает развитие репозитория."
            ),
            (
                "Лицензия Apache-2.0 · © 2026 ai-interview-atlas contributors. Пересказанный "
                "материал из лицензированных подборок указан на странице источников."
            ),
        ],
        "back": "← [AI Interview Atlas]({readme})",
        "crumbs": "[AI Interview Atlas]({readme}) › [{section}]({hub})",
        "navigate": "**Навигация:**",
        "map": "Карта атласа",
        "map_intro": (
            "Все страницы атласа в одном месте. Начните с приоритетных вопросов своего трека, "
            "затем углубляйтесь по темам или по работодателям."
        ),
        "start_short": "С чего начать: {track}",
        "start_name": "С чего начать",
        "answers_name": "Ответы",
        "start_summary": "приоритетные вопросы в порядке изучения: {count}",
        "answers_summary": "готово {done} из {total}",
        "theme_summary": "О чём",
        "reference": "Справка",
        "reference_items": [
            (
                "common",
                "Спрашивают в нескольких компаниях",
                "вопросы, о которых сообщали в двух и более компаниях",
            ),
            ("radar", "Радар требований", "что требуют вакансии, по темам"),
            ("learning_path", "Учебный план", "программа подготовки с еженедельной практикой"),
            (
                "learning_roadmap",
                "Карта обучения",
                "Выберите предметный маршрут в дополнение к существующему восьминедельному плану",
            ),
            (
                "ai_assisted_coding",
                "AI-ассистированный кодинг",
                "Четыре недели чтения кода, ограниченной помощи AI, тестирования и ревью",
            ),
            (
                "production_ai_engineering",
                "Прикладная AI-инженерия",
                "Восемь недель контрактов, оценки, поиска, инструментов и эксплуатации",
            ),
            (
                "ai_leadership",
                "AI Leadership",
                "Восьминедельный маршрут по решениям, свидетельствам и реализации",
            ),
            (
                "coverage_audit",
                "Аудит покрытия",
                "Покрытие репозитория, границы свидетельств и оставшиеся пробелы",
            ),
            (
                "engineering_research",
                "Исследование Engineering",
                "Сравнение источников и обоснование двух маршрутов Engineering",
            ),
            (
                "leadership_audit",
                "Аудит Leadership",
                "Свидетельства и учебное покрытие лидерских обязанностей",
            ),
            (
                "atlas_expansion",
                "План расширения",
                "Приоритеты, зависимости и критерии приёмки дальнейшей работы",
            ),
            (
                "reasoning_models",
                "Reasoning-модели",
                "вычислительный бюджет, оценка и ограничения трасс рассуждений",
            ),
            (
                "ai_roles",
                "Профессии в AI",
                "шесть направлений: задачи, собеседования, вопросы и подготовка",
            ),
            ("methodology", "Методика", "что считается источником и что означают метки"),
            (
                "sources",
                "Источники",
                "все страницы, на которые ссылается атлас, с датой проверки",
            ),
            ("attribution", "Атрибуция", "исходные материалы, переработка и лицензии"),
            ("roadmap", "Дорожная карта", "что будет дальше и чего проект делать не будет"),
            ("changelog", "Журнал изменений", "что менялось в каждом издании"),
            (
                "contributing",
                "Как участвовать",
                "сообщить о проблеме или добавить вопрос с датированным публичным источником",
            ),
            ("pdf", "PDF-издания", "тот же материал в виде книг для печати"),
        ],
        "on_page": "На этой странице",
        "roles_title": "Профессии в AI: задачи, собеседования и подготовка",
        "roles_checked": (
            "Вакансии проверены {date}. Они описывают обязанности, а не то, как проходят "
            "собеседования."
        ),
        "roles_overview": "Обзор",
        "role_family": "Направление",
        "role_owns": "Чем занимается",
        "role_stages": "Этапы из источников",
        "role_companies": "Компании",
        "role_reported_count": "Вопросы из источников",
        "role_practice_count": "Вопросы для практики",
        "role_pages": "Страницы профессий",
        "role_scope": "Чем занимается роль",
        "role_sources": "Источники",
        "role_interviews": "Как проходит собеседование",
        "role_interviews_intro": (
            "Этапы, о которых источники сообщают для этих ролей, со страниц компаний. Метки "
            "показывают основание; процессы собеседований меняются, поэтому смотрите даты."
        ),
        "role_no_interviews": (
            "Публичных данных о собеседованиях на эти роли пока нет. Вакансия описывает работу, "
            "но не показывает, как проходят собеседования."
        ),
        "role_company_pages": "Страницы компаний, где есть эти роли: {links}.",
        "role_reported": "Сообщали для этих ролей",
        "role_reported_intro": (
            "Вопросы, источник которых указывает, что их задавали на одну из этих ролей."
        ),
        "role_practice": "Для практики",
        "role_practice_intro": (
            "Редакционная подборка: вопросы по теме роли, о которых не сообщали именно для неё."
        ),
        "role_no_questions": "Вопросов для этих ролей пока нет.",
        "role_prep": "Подготовка",
        "role_route": "Маршрут подготовки",
        "role_deliverable": "Практический результат",
        "checklist": "Чек-лист",
        "answer_link": "✍ [Ответ]({page})",
        "fix": "Предложить правку",
        "fix_title": "[Correction] {id}",
        "contents": "Содержание",
        "to_contents": "[↑ К содержанию](#contents)",
        "asked_at": "Где спрашивали",
        "tests": "Что проверяет",
        "covers": "Сильный ответ покрывает",
        "read": "Читать",
        "generated": "сгенерировано по темам вакансий",
        "both": "Оба трека",
        "roles": "Роли",
        "loop": "Этапы интервью",
        "stage": "Этап",
        "what": "Что происходит",
        "basis": "Основание",
        "prep": "Официальные материалы для подготовки",
        "reported": "Вопросы, о которых сообщали для {company}",
        "none_reported": "Вопросов по этой компании пока нет.",
        "last_reviewed": "Этапы проверены {date}",
        "stale": "⚠️ старше года",
        "radar_title": "Радар требований",
        "period": "Период",
        "sample": "Выборка",
        "sample_value": (
            "{postings} вакансий: инженерия — {engineering}, лидерство — {leadership}"
        ),
        "market_value": "рынки: международный — {intl}, Россия — {ru}, не указан — {unknown}",
        "method": "Методика",
        "criteria": "Что засчитывается в каждой теме",
        "suppressed": (
            "Прочерк: тему упоминают меньше {min_cell} вакансий или в треке меньше {min_track} "
            "вакансий; такие ячейки не публикуются."
        ),
        "share": "{share}% ({postings})",
        "sources_title": "Источники и атрибуция",
        "retrieved": "проверено",
        "published": "опубликовано",
        "license": "лицензия",
        "attribution": (
            "Вопросы с меткой †, взятые из {title} ({publisher}), пересказаны своими словами "
            "со ссылкой на источник; подборка распространяется по лицензии {license}."
        ),
        "svg_title": "Доля вакансий, где упоминается тема",
        "ai_share": (
            "Вакансии трека «{track}» в выборке: сама роль связана с AI или машинным "
            "обучением в {share}% ({count} из {total})."
        ),
        "sample_names": {"engineering": "инженерия", "leadership": "лидерство"},
        "types": {
            "knowledge": "Знания",
            "coding": "Кодинг",
            "system_design": "System design",
            "product_case": "Продуктовый кейс",
            "applied_scenario": "Прикладной сценарий",
            "leadership": "Руководство",
            "behavioral": "Поведенческий",
            "self_presentation": "Самопрезентация",
        },
        "levels": {"mid": "Middle", "senior": "Senior", "staff": "Staff+", "director": "Director+"},
        "segments": {
            "frontier-lab": "Лаборатории frontier-AI",
            "big-tech": "Бигтех",
            "ai-infra": "AI-инфраструктура",
            "ai-native": "AI-native продукты",
            "enterprise-ai": "Корпоративный и forward-deployed AI",
            "fintech": "Финтех и платежи",
            "ru-big-tech": "Бигтех России",
        },
        "market_names": {"intl": "Международный", "ru": "Россия"},
        "claims": {
            "confirmed": "✅ подтверждено компанией",
            "participant_report": "🗣 отчёт кандидата",
            "secondary": "† гайд или подборка",
            "assumption": "❔ предположение",
        },
        "coding_values": {
            "required": "обязателен",
            "not_required": "не требуется",
            "varies": "зависит от роли",
            "unknown": "неизвестно",
        },
        "kinds": {
            "official": "Источники компаний",
            "participant_report": "Отчёты кандидатов",
            "prep_guide": "Гайды по подготовке",
            "secondary_compilation": "Подборки",
            "reference": "Справочные материалы",
            "posting": "Вакансии (только описание роли)",
        },
    },
}


def readme(lang: str) -> str:
    return "README.md" if lang == "en" else "README.ru.md"


def base(lang: str) -> str:
    return "docs" if lang == "en" else "docs/ru"


def theme_page(lang: str, theme: str) -> str:
    return f"{base(lang)}/themes/{theme}.md"


def company_page(lang: str, company: str) -> str:
    return f"{base(lang)}/companies/{company}.md"


def start_page(lang: str, track: str) -> str:
    return f"{base(lang)}/start/{track}.md"


def common_page(lang: str) -> str:
    return f"{base(lang)}/common.md"


def answers_page(lang: str, track: str) -> str:
    return f"{base(lang)}/answers/{track}.md"


def radar_page(lang: str) -> str:
    return f"{base(lang)}/radar.md"


def sources_page(lang: str) -> str:
    return f"{base(lang)}/sources.md"


def methodology_page(lang: str) -> str:
    return f"{base(lang)}/METHODOLOGY.md"


def hub_page(lang: str) -> str:
    return f"{base(lang)}/README.md"


def roles_page(lang: str) -> str:
    return f"{base(lang)}/AI_ROLES.md"


def role_page(lang: str, family: str) -> str:
    return f"{base(lang)}/roles/{family}.md"


# Targets of [label](page:key) links in the AI roles guide.
ROLE_PAGE_PATHS = {
    "learning-path": lambda lang: f"{base(lang)}/LEARNING_PATH.md",
    "reasoning-models": lambda lang: f"{base(lang)}/REASONING_MODELS.md",
    "methodology": methodology_page,
    "roadmap": lambda lang: f"{base(lang)}/ROADMAP.md",
    "radar": radar_page,
    "sources": sources_page,
    "roles": roles_page,
}


def changelog_page(lang: str) -> str:
    return "CHANGELOG.md" if lang == "en" else "docs/ru/CHANGELOG.md"


def contributing_page(lang: str) -> str:
    return "CONTRIBUTING.md" if lang == "en" else "CONTRIBUTING.ru.md"


def fix_url(question_id: str, lang: str) -> str:
    """A correction issue form with the question id filled in."""
    title = quote(LABELS[lang]["fix_title"].format(id=question_id))
    return f"{REPO}/issues/new?template=correction.yml&question={question_id}&title={title}"


def reference_name(lang: str, key: str) -> str:
    """The display name of a reference page on the map of the atlas."""
    return next(name for item, name, _ in LABELS[lang]["reference_items"] if item == key)


def anchor(name: str) -> str:
    """An explicit anchor: stable on GitHub and the site, unlike heading slugs in Cyrillic."""
    return f'<a id="{name}"></a>'


def svg_file(lang: str) -> str:
    return f"docs/assets/radar.{lang}.svg"


def other(lang: str) -> str:
    return "ru" if lang == "en" else "en"


def rel(page: str, target: str) -> str:
    return posixpath.relpath(target, posixpath.dirname(page) or ".")


def md(text: str) -> str:
    return text.replace("<", "&lt;").replace(">", "&gt;").strip()


def cell(text: str) -> str:
    return md(text).replace("|", "\\|").replace("\n", " ")


def percent(part: int, whole: int) -> int:
    return round(100 * part / whole) if whole else 0


class Renderer:
    def __init__(self, content: Content):
        self.content = content
        self.theme_order = {t["id"]: i for i, t in enumerate(content.taxonomy["themes"])}
        self.track_names = {t["id"]: t["name"] for t in content.taxonomy["tracks"]}
        self.question_by_id = {q["id"]: q for q in content.questions}

    def pages(self) -> dict[str, str]:
        pages: dict[str, str] = {}
        for lang in LANGS:
            pages[readme(lang)] = self.readme(lang)
            pages[hub_page(lang)] = self.hub(lang)
            for theme in self.content.taxonomy["themes"]:
                pages[theme_page(lang, theme["id"])] = self.theme(lang, theme)
            for company in self.content.companies.values():
                pages[company_page(lang, company["id"])] = self.company(lang, company)
            for track in TRACKS:
                # Always generated: the README links a start page for every track.
                pages[start_page(lang, track)] = self.start(lang, track)
                if self.answered(lang, track):
                    pages[answers_page(lang, track)] = self.answers(lang, track)
            if self.common():
                pages[common_page(lang)] = self.common_questions(lang)
            pages[sources_page(lang)] = self.sources(lang)
            if self.content.families:
                pages[roles_page(lang)] = self.roles_overview(lang)
                for family in self.content.families:
                    pages[role_page(lang, family["id"])] = self.role(lang, family)
            if self.content.radar:
                pages[radar_page(lang)] = self.radar(lang)
                pages[svg_file(lang)] = self.svg(lang)
        return {path: text.rstrip("\n") + "\n" for path, text in sorted(pages.items())}

    # Shared pieces

    def switch(self, lang: str, page: str, counterpart: str) -> str:
        return LABELS[lang]["switch"].format(other=rel(page, counterpart))

    def crumbs(self, lang: str, page: str, section: str | None = None) -> str:
        """Where a page sits: the atlas, then its section on the map of the atlas."""
        labels, hub = LABELS[lang], rel(page, hub_page(lang))
        if section == "roles":
            return labels["crumbs"].format(
                readme=rel(page, readme(lang)),
                section=reference_name(lang, "ai_roles"),
                hub=rel(page, roles_page(lang)),
            )
        names = {
            "tracks": labels["tracks"],
            "themes": labels["themes"],
            "companies": labels["companies"],
            "reference": labels["reference"],
        }
        return labels["crumbs"].format(
            readme=rel(page, readme(lang)),
            section=names[section] if section else labels["map"],
            hub=f"{hub}#{section}" if section else hub,
        )

    def header(
        self, lang: str, page: str, counterpart: str | None, section: str | None = None
    ) -> str:
        crumbs = self.crumbs(lang, page, section)
        return self.switch(lang, page, counterpart) + " · " + crumbs if counterpart else crumbs

    @staticmethod
    def pager(page: str, items: list[tuple[str, str]], current: str) -> list[str]:
        """Previous and next page in a fixed order, as a footer line."""
        paths = [path for _, path in items]
        index = paths.index(current)
        parts = []
        if index > 0:
            name, path = items[index - 1]
            parts.append(f"← [{name}]({rel(page, path)})")
        if index < len(items) - 1:
            name, path = items[index + 1]
            parts.append(f"[{name}]({rel(page, path)}) →")
        return ["", " · ".join(parts)] if parts else []

    def company_name(self, company: str, lang: str) -> str:
        return self.content.companies[company]["name"][lang]

    def asked_at(self, question: dict, lang: str, page: str, current: str | None = None) -> str:
        """Companies that asked, strongest basis first; the page's own company is not a link."""
        found = self.content.asked_at(question)
        ordered = sorted(
            found.items(), key=lambda item: (STRENGTH[item[1]], self.company_name(item[0], lang))
        )
        return ", ".join(
            (
                self.company_name(company, lang)
                if company == current
                else f"[{self.company_name(company, lang)}]"
                f"({rel(page, company_page(lang, company))})"
            )
            + f" {MARKERS[kind]}"
            for company, kind in ordered
        )

    def answer_link(self, question: dict, lang: str, page: str, track: str | None = None) -> str:
        """Link to the written answer, on the given track's answers page when it has one."""
        if not question.get("answer", {}).get(lang):
            return ""
        tracks = question.get("start_here", [])
        chosen = track if track in tracks else next((t for t in TRACKS if t in tracks), None)
        if not chosen:
            return ""
        target = f"{rel(page, answers_page(lang, chosen))}#{question['id']}"
        return LABELS[lang]["answer_link"].format(page=target)

    def question(
        self,
        question: dict,
        lang: str,
        page: str,
        *,
        full: bool = True,
        theme_link: bool = False,
        number: int | None = None,
        canonical: bool = False,
        track: str | None = None,
        company: str | None = None,
    ) -> list[str]:
        """One question. Its theme page holds the anchor; every other page links to it."""
        labels = LABELS[lang]
        meta = [labels["types"][question["type"]]]
        if question.get("level"):
            meta.append(labels["levels"][question["level"]])
        if theme_link:
            theme = self.content.themes[question["theme"]]
            meta.append(f"[{theme['name'][lang]}]({rel(page, theme_page(lang, theme['id']))})")
        asked = self.asked_at(question, lang, page, current=company)
        if asked:
            meta.append(f"{labels['asked_at']}: {asked}")
        if question["provenance"] == "generated":
            meta.append(f"🧪 {labels['generated']}")
        answer = self.answer_link(question, lang, page, track)
        if answer:
            meta.append(answer)
        if canonical:
            meta.append(f"[{labels['fix']}]({fix_url(question['id'], lang)})")
        label = f"{number}. " if number else ""
        text = md(question["text"][lang])
        if canonical:
            head = f"- {anchor(question['id'])}**{label}{text}**"
        else:
            home = rel(page, theme_page(lang, question["theme"]))
            head = f"- **{label}[{text}]({home}#{question['id']})**"
        lines = [head, f"  - {' · '.join(meta)}"]
        if not full:
            return lines
        lines.append(f"  - {labels['tests']}: {md(question['tests'][lang])}")
        if question.get("outline"):
            lines.append(f"  - {labels['covers']}:")
            lines += [f"    - {md(point)}" for point in question["outline"][lang]]
        if question.get("reading"):
            links = []
            for source_id in question["reading"]:
                source = self.content.sources[source_id]
                links.append(f"[{cell(source['title'])}]({source['url']}) ({source['publisher']})")
            lines.append(f"  - {labels['read']}: " + " · ".join(links))
        return lines

    def reviewed(self, company: dict, lang: str) -> str:
        """Review date, flagged when a year older than the newest content (not today's date)."""
        newest = date.fromisoformat(self.updated())
        stale = date.fromisoformat(company["reviewed"]) < newest - timedelta(days=365)
        return company["reviewed"] + (f" {LABELS[lang]['stale']}" if stale else "")

    def updated(self) -> str:
        content = self.content
        dates = [q["added"] for q in content.questions]
        dates += [c["reviewed"] for c in content.companies.values()]
        dates += [s["retrieved"] for s in content.sources.values()]
        return max(dates) if dates else ""

    def start_here(self, track: str) -> list[dict]:
        chosen = [q for q in self.content.questions if track in q.get("start_here", [])]
        return sorted(chosen, key=lambda q: (q.get("priority", 999), self.theme_order[q["theme"]]))

    def answered(self, lang: str, track: str) -> list[dict]:
        """Priority questions of this track that already have an answer in this language."""
        return [q for q in self.start_here(track) if q.get("answer", {}).get(lang)]

    # Pages

    def answers(self, lang: str, track: str) -> str:
        labels, page = LABELS[lang], answers_page(lang, track)
        name = self.track_names[track][lang]
        chosen, all_priority = self.answered(lang, track), self.start_here(track)
        # The other language has its own page only once it has answers of its own.
        counterpart = answers_page(other(lang), track)
        lines = [
            HEADER,
            f"# {labels['answers'].format(track=name)}",
            "",
            self.header(
                lang, page, counterpart if self.answered(other(lang), track) else None, "tracks"
            ),
            "",
            md(labels["answers_intro"]),
            "",
            labels["answers_progress"].format(done=len(chosen), total=len(all_priority)),
        ]
        numbers = {q["id"]: number for number, q in enumerate(all_priority, 1)}
        # Contents grouped by theme, in the order the themes first appear.
        lines += ["", f"## {anchor('contents')}{labels['contents']}", ""]
        themes: dict[str, list[dict]] = {}
        for question in chosen:
            themes.setdefault(question["theme"], []).append(question)
        for theme_id, grouped in themes.items():
            lines.append(f"- **{md(self.content.themes[theme_id]['name'][lang])}**")
            lines += [
                f"  - [{numbers[q['id']]}. {md(q['text'][lang])}](#{q['id']})" for q in grouped
            ]
        for question in chosen:
            theme = self.content.themes[question["theme"]]
            link = rel(page, theme_page(lang, theme["id"]))
            lines += [
                "",
                (
                    f"### {anchor(question['id'])}{numbers[question['id']]}. "
                    f"{md(question['text'][lang])}"
                ),
                "",
                (
                    f"*{labels['types'][question['type']]} · [{md(theme['name'][lang])}]({link}) · "
                    f"[{labels['checklist']}]({link}#{question['id']})*"
                ),
                "",
                md(question["answer"][lang]),
            ]
            if question.get("reading"):
                links = []
                for source_id in question["reading"]:
                    source = self.content.sources[source_id]
                    links.append(f"[{cell(source['title'])}]({source['url']})")
                lines += ["", f"{labels['read']}: " + " · ".join(links)]
            lines += ["", labels["to_contents"]]
        return "\n".join(lines)

    def common(self) -> list[dict]:
        """Questions reported at two or more companies."""
        return [q for q in self.content.questions if len(self.content.asked_at(q)) >= 2]

    def start(self, lang: str, track: str) -> str:
        labels, page = LABELS[lang], start_page(lang, track)
        name = self.track_names[track][lang]
        lines = [
            HEADER,
            f"# {labels['start'].format(track=name)}",
            "",
            self.header(lang, page, start_page(other(lang), track), "tracks"),
            "",
            md(labels["start_intro"]),
            "",
            labels["learning_path"].format(page=rel(page, f"{base(lang)}/LEARNING_PATH.md")),
        ]
        lines += self._learning_links(lang, page)
        if self.answered(lang, track):
            link = rel(page, answers_page(lang, track))
            lines += ["", labels["answers_link"].format(page=link)]
        lines.append("")
        for number, question in enumerate(self.start_here(track), 1):
            lines += self.question(
                question, lang, page, full=False, theme_link=True, number=number, track=track
            )
        return "\n".join(lines)

    def common_questions(self, lang: str) -> str:
        labels, page = LABELS[lang], common_page(lang)
        lines = [
            HEADER,
            f"# {labels['common']}",
            "",
            self.header(lang, page, common_page(other(lang)), "reference"),
            "",
            labels["common_intro"],
        ]
        for theme in self.content.taxonomy["themes"]:
            chosen = [q for q in self.common() if q["theme"] == theme["id"]]
            if chosen:
                link = rel(page, theme_page(lang, theme["id"]))
                lines += ["", f"## [{theme['name'][lang]}]({link})", ""]
                for question in chosen:
                    lines += self.question(question, lang, page, full=False)
        return "\n".join(lines)

    def readme(self, lang: str) -> str:
        labels, content, page = LABELS[lang], self.content, readme(lang)
        counts = {track: sum(track in q["tracks"] for q in content.questions) for track in TRACKS}
        names = {track: self.track_names[track][lang] for track in TRACKS}
        answered = sum(1 for q in content.questions if q.get("answer", {}).get(lang))
        lines = [
            HEADER,
            "# AI Interview Atlas",
            "",
            self.switch(lang, page, readme(other(lang))),
            "",
            f"![{labels['banner_alt']}]({BANNER})",
            "",
            BADGES,
            "",
            self.navigation(lang),
            "",
            f"**{labels['hero']}**",
            "",
            labels["intro"],
            "",
            self._source_mix(lang, page),
            "",
            labels["offline"].format(releases=RELEASES),
            "",
            f"## {labels['inside']}",
            "",
        ]
        for item in labels["inside_items"]:
            if "{answers}" in item and not answered:
                lines.append(f"- {labels['answers_pending']}")
                continue
            if "{families}" in item and not content.families:
                continue
            lines.append(
                "- "
                + item.format(
                    questions=len(content.questions),
                    themes=len(content.taxonomy["themes"]),
                    companies=len(content.companies),
                    sources=len(content.sources),
                    answers=answered,
                    families=len(content.families),
                    roles_page=roles_page(lang),
                    questions_word=ru_count(
                        len(content.questions), "вопрос", "вопроса", "вопросов"
                    ),
                    answers_word=ru_count(
                        answered,
                        "написанный ответ",
                        "написанных ответа",
                        "написанных ответов",
                    ),
                    companies_word=ru_count(
                        len(content.companies), "страница", "страницы", "страниц"
                    ),
                    families_word=ru_count(
                        len(content.families), "страница", "страницы", "страниц"
                    ),
                    sources_word=ru_count(
                        len(content.sources), "источник", "источника", "источников"
                    ),
                    **counts,
                )
            )
        lines += ["", f"## {labels['different']}", ""]
        lines += [f"- {item}" for item in labels["different_items"]]
        lines += ["", f"## {labels['quickstart']}", ""]
        pages = {f"{track}_page": rel(page, start_page(lang, track)) for track in TRACKS}
        for index, item in enumerate(labels["quickstart_items"], 1):
            lines.append(
                f"{index}. "
                + item.format(
                    engineering_name=names["engineering"],
                    leadership_name=names["leadership"],
                    **pages,
                )
            )
        lines += [
            "",
            labels["learning_path"].format(page=rel(page, f"{base(lang)}/LEARNING_PATH.md")),
            *self._learning_links(lang, page),
            "",
            labels["legend"],
            "",
            f"## {labels['tracks']}",
            "",
        ]
        for track in content.taxonomy["tracks"]:
            roles = [
                r["name"][lang] for r in content.taxonomy["roles"] if r["track"] == track["id"]
            ]
            lines.append(f"- **{track['name'][lang]}.** {md(track['summary'][lang])}")
            lines.append(f"  - {', '.join(roles)}")
            lines += self.role_pages_line(lang, page, track["id"])
        if self.common():
            link = rel(page, common_page(lang))
            lines += ["", f"## [{labels['common']}]({link})", "", labels["common_intro"]]
        lines += [
            "",
            f"## {labels['themes']}",
            "",
            f"| {labels['theme']} | {names['engineering']} | {names['leadership']} |",
            "| --- | ---: | ---: |",
        ]
        for theme in content.taxonomy["themes"]:
            in_theme = [q for q in content.questions if q["theme"] == theme["id"]]
            per_track = [sum(track in q["tracks"] for q in in_theme) for track in TRACKS]
            link = rel(page, theme_page(lang, theme["id"]))
            lines.append(
                f"| [{cell(theme['name'][lang])}]({link}) | {per_track[0]} | {per_track[1]} |"
            )
        if content.companies:
            lines += [
                "",
                f"## {labels['companies']}",
                "",
                (
                    f"| {labels['company']} | {labels['segment']} | {labels['markets']} "
                    f"| {labels['coding']} | {labels['questions']} | {labels['reviewed']} |"
                ),
                "| --- | --- | --- | --- | ---: | --- |",
            ]
            for company in self.companies_in_order(lang):
                asked = sum(company["id"] in content.asked_at(q) for q in content.questions)
                markets = ", ".join(labels["market_names"][m] for m in company["markets"])
                link = rel(page, company_page(lang, company["id"]))
                lines.append(
                    f"| [{cell(company['name'][lang])}]({link}) "
                    f"| {labels['segments'][company['segment']]} | {markets} "
                    f"| {labels['coding_values'][company['coding']['value']]} | {asked} "
                    f"| {self.reviewed(company, lang)} |"
                )
        if content.radar:
            radar = content.radar
            lines += [
                "",
                f"## {labels['radar']}",
                "",
                labels["radar_intro"].format(
                    postings=radar["sample"]["postings"],
                    engineering=radar["sample"]["tracks"].get("engineering", 0),
                    leadership=radar["sample"]["tracks"].get("leadership", 0),
                    min_track=radar["min_track"],
                    start=radar["period"]["from"],
                    end=radar["period"]["to"],
                    page=radar_page(lang),
                ),
                *self.ai_share(lang),
                "",
                f"![{labels['svg_title']}]({svg_file(lang)})",
            ]
        lines += ["", f"## {labels['about']}", ""]
        for item in labels["about_items"]:
            lines.append(
                "- "
                + item.format(
                    methodology=methodology_page(lang),
                    sources=sources_page(lang),
                    attribution=f"{base(lang)}/ATTRIBUTION.md",
                    roadmap=f"{base(lang)}/ROADMAP.md",
                    learning_path=f"{base(lang)}/LEARNING_PATH.md",
                )
            )
        return "\n".join(lines)

    def _source_mix(self, lang: str, page: str) -> str:
        """Count question provenance independently from technical reading links.

        The largest compilation is named, and linked to its attribution on the sources page
        rather than to the external repository.
        """
        content, labels = self.content, LABELS[lang]
        published = [q for q in content.questions if q["provenance"] == "published"]
        secondary_only = sum(
            all(
                content.sources[e["source"]]["kind"] in {"prep_guide", "secondary_compilation"}
                for e in q["evidence"]
            )
            for q in published
        )
        text = labels["source_mix"].format(
            published=len(published),
            secondary_only=secondary_only,
            generated=len(content.questions) - len(published),
        )
        compilations = Counter(
            source
            for q in published
            for source in {
                e["source"]
                for e in q["evidence"]
                if content.sources[e["source"]]["kind"] == "secondary_compilation"
            }
        )
        if compilations:
            source, count = min(compilations.items(), key=lambda item: (-item[1], item[0]))
            target = f"{rel(page, sources_page(lang))}#kind-secondary-compilation"
            link = f"[{content.sources[source]['title']}]({target})"
            text += " " + labels["source_concentration"].format(
                largest_source_questions=count, largest_source_link=link
            )
        return text

    def _learning_links(self, lang: str, page: str) -> list[str]:
        targets = {key: rel(page, f"{base(lang)}/{path}") for key, path in _GUIDE_PATHS.items()}
        return [
            "",
            LABELS[lang]["learning_routes"].format(**targets),
            "",
            LABELS[lang]["learning_evidence"].format(**targets),
        ]

    def navigation(self, lang: str) -> str:
        """The README's one-line menu: the map, both start pages and the main sections."""
        labels, page = LABELS[lang], readme(lang)
        items = [f"[{labels['map']}]({hub_page(lang)})"]
        items += [
            f"[{labels['start_short'].format(track=self.track_names[track][lang])}]"
            f"({start_page(lang, track)})"
            for track in TRACKS
        ]
        items.append(f"[{labels['themes']}](#{self.slug(labels['themes'])})")
        if self.content.companies:
            items.append(f"[{labels['companies']}](#{self.slug(labels['companies'])})")
        for key in ("learning_path", "ai_roles", "reasoning_models"):
            items.append(
                f"[{reference_name(lang, key)}]({rel(page, f'{base(lang)}/{key.upper()}.md')})"
            )
        items.append(f"[PDF]({RELEASES})")
        return f"{labels['navigate']} " + " · ".join(items)

    @staticmethod
    def slug(heading: str) -> str:
        """GitHub's anchor for a plain heading without punctuation."""
        return heading.strip().lower().replace(" ", "-")

    def hub(self, lang: str) -> str:
        """Map of the atlas: every generated and hand-written page, grouped by purpose."""
        labels, content, page = LABELS[lang], self.content, hub_page(lang)
        lines = [
            HEADER,
            f"# {labels['map']}",
            "",
            self.switch(lang, page, hub_page(other(lang)))
            + " · "
            + labels["back"].format(readme=rel(page, readme(lang))),
            "",
            labels["map_intro"],
            "",
            self._source_mix(lang, page),
            "",
            labels["legend"],
            "",
            f"## {anchor('tracks')}{labels['tracks']}",
            "",
        ]
        for track in content.taxonomy["tracks"]:
            priority = self.start_here(track["id"])
            lines.append(f"- **{track['name'][lang]}.** {md(track['summary'][lang])}")
            roles = [
                r["name"][lang] for r in content.taxonomy["roles"] if r["track"] == track["id"]
            ]
            if roles:
                lines.append(f"  - {labels['roles']}: {', '.join(roles)}")
            lines += self.role_pages_line(lang, page, track["id"])
            start = rel(page, start_page(lang, track["id"]))
            lines.append(
                f"  - [{labels['start_name']}]({start}): "
                + labels["start_summary"].format(count=len(priority))
            )
            done = self.answered(lang, track["id"])
            if done:
                answers = rel(page, answers_page(lang, track["id"]))
                lines.append(
                    f"  - [{labels['answers_name']}]({answers}): "
                    + labels["answers_summary"].format(done=len(done), total=len(priority))
                )
        names = {track: self.track_names[track][lang] for track in TRACKS}
        lines += [
            "",
            f"## {anchor('themes')}{labels['themes']}",
            "",
            (
                f"| {labels['theme']} | {labels['theme_summary']} "
                f"| {names['engineering']} | {names['leadership']} |"
            ),
            "| --- | --- | ---: | ---: |",
        ]
        for theme in content.taxonomy["themes"]:
            in_theme = [q for q in content.questions if q["theme"] == theme["id"]]
            per_track = [sum(track in q["tracks"] for q in in_theme) for track in TRACKS]
            link = rel(page, theme_page(lang, theme["id"]))
            lines.append(
                f"| [{cell(theme['name'][lang])}]({link}) | {cell(theme['summary'][lang])} "
                f"| {per_track[0]} | {per_track[1]} |"
            )
        if content.companies:
            lines += ["", f"## {anchor('companies')}{labels['companies']}", ""]
            for segment in SEGMENTS:
                chosen = [c for c in self.companies_in_order(lang) if c["segment"] == segment]
                if chosen:
                    links = " · ".join(
                        f"[{c['name'][lang]}]({rel(page, company_page(lang, c['id']))})"
                        for c in chosen
                    )
                    lines.append(f"- **{labels['segments'][segment]}:** {links}")
        targets = {
            "common": common_page(lang) if self.common() else None,
            "radar": radar_page(lang) if content.radar else None,
            "learning_path": f"{base(lang)}/LEARNING_PATH.md",
            "ai_roles": f"{base(lang)}/AI_ROLES.md",
            "reasoning_models": f"{base(lang)}/REASONING_MODELS.md",
            "methodology": methodology_page(lang),
            "sources": sources_page(lang),
            "attribution": f"{base(lang)}/ATTRIBUTION.md",
            "roadmap": f"{base(lang)}/ROADMAP.md",
            "changelog": changelog_page(lang),
            "contributing": contributing_page(lang),
            **{key: f"{base(lang)}/{path}" for key, path in _GUIDE_PATHS.items()},
        }
        lines += ["", f"## {anchor('reference')}{labels['reference']}", ""]
        for key, name, summary in labels["reference_items"]:
            if key == "pdf":
                lines.append(f"- [{name}]({RELEASES}): {summary}.")
            elif targets[key]:
                lines.append(f"- [{name}]({rel(page, targets[key])}): {summary}.")
        return "\n".join(lines)

    def companies_in_order(self, lang: str) -> list[dict]:
        return sorted(
            self.content.companies.values(),
            key=lambda c: (SEGMENTS.index(c["segment"]), c["name"][lang].casefold()),
        )

    def theme(self, lang: str, theme: dict) -> str:
        labels, page = LABELS[lang], theme_page(lang, theme["id"])
        questions = [q for q in self.content.questions if q["theme"] == theme["id"]]
        lines = [
            HEADER,
            f"# {theme['name'][lang]}",
            "",
            self.header(lang, page, theme_page(other(lang), theme["id"]), "themes"),
            "",
            md(theme["summary"][lang]),
        ]
        groups = [
            ("both", labels["both"], lambda q: set(q["tracks"]) == set(TRACKS)),
            (
                "engineering",
                self.track_names["engineering"][lang],
                lambda q: q["tracks"] == ["engineering"],
            ),
            (
                "leadership",
                self.track_names["leadership"][lang],
                lambda q: q["tracks"] == ["leadership"],
            ),
        ]
        sections = [
            (key, title, [q for q in questions if belongs(q)]) for key, title, belongs in groups
        ]
        sections = [section for section in sections if section[2]]
        if len(sections) > 1:
            contents = " · ".join(
                f"[{title} ({len(chosen)})](#track-{key})" for key, title, chosen in sections
            )
            lines += ["", f"{labels['on_page']}: {contents}"]
        for key, title, chosen in sections:
            lines += ["", f"## {anchor(f'track-{key}')}{title}", ""]
            for question in chosen:
                lines += self.question(question, lang, page, canonical=True)
        order = [
            (t["name"][lang], theme_page(lang, t["id"])) for t in self.content.taxonomy["themes"]
        ]
        lines += self.pager(page, order, page)
        return "\n".join(lines)

    def company(self, lang: str, company: dict) -> str:
        labels, content = LABELS[lang], self.content
        page = company_page(lang, company["id"])
        name = company["name"][lang]
        markets = ", ".join(labels["market_names"][m] for m in company["markets"])
        lines = [
            HEADER,
            f"# {name}",
            "",
            self.header(lang, page, company_page(other(lang), company["id"]), "companies"),
            "",
            f"{labels['segments'][company['segment']]} · {markets} · "
            + labels["last_reviewed"].format(date=self.reviewed(company, lang)),
        ]
        if company.get("summary"):
            lines += ["", md(company["summary"][lang])]
        reported = [q for q in content.questions if company["id"] in content.asked_at(q)]
        contents = [f"[{labels['loop']}](#loop)"]
        if company.get("prep"):
            contents.append(f"[{labels['prep']}](#prep)")
        contents.append(f"[{labels['questions']} ({len(reported)})](#questions)")
        lines += ["", f"{labels['on_page']}: " + " · ".join(contents)]
        lines += ["", f"## {labels['roles']}", ""]
        for track in TRACKS:
            roles = [content.roles[r]["name"][lang] for r in company["roles"].get(track, [])]
            if roles:
                lines.append(f"- **{self.track_names[track][lang]}:** {', '.join(roles)}")
        lines += [
            "",
            f"## {anchor('loop')}{labels['loop']}",
            "",
            f"| {labels['stage']} | {labels['what']} | {labels['basis']} |",
            "| --- | --- | --- |",
        ]
        for stage in company["loop"]:
            basis = [labels["claims"][stage["claim"]]]
            basis += [self.source_link(s, lang) for s in stage.get("sources", [])]
            detail = cell(stage["detail"][lang]) if stage.get("detail") else ""
            lines.append(f"| {self.stage_name(stage, lang)} | {detail} | {'<br>'.join(basis)} |")
        coding = company["coding"]
        coding_line = f"**{labels['coding']}:** {labels['coding_values'][coding['value']]}"
        if coding.get("note"):
            coding_line += f". {md(coding['note'][lang])}"
        if coding.get("sources"):
            coding_line += (
                " (" + ", ".join(self.source_link(s, lang) for s in coding["sources"]) + ")"
            )
        lines += ["", coding_line]
        if company.get("prep"):
            lines += ["", f"## {anchor('prep')}{labels['prep']}", ""]
            lines += [f"- {self.source_link(s, lang)}" for s in company["prep"]]
        lines += ["", f"## {anchor('questions')}{labels['reported'].format(company=name)}"]
        if not reported:
            lines += ["", labels["none_reported"]]
        for theme in content.taxonomy["themes"]:
            chosen = [q for q in reported if q["theme"] == theme["id"]]
            if chosen:
                link = rel(page, theme_page(lang, theme["id"]))
                lines += ["", f"### [{theme['name'][lang]}]({link})", ""]
                for question in chosen:
                    lines += self.question(question, lang, page, company=company["id"])
        order = [
            (c["name"][lang], company_page(lang, c["id"])) for c in self.companies_in_order(lang)
        ]
        lines += self.pager(page, order, page)
        return "\n".join(lines)

    def stage_name(self, stage: dict, lang: str) -> str:
        """A loop stage's name, with the roles it was reported for when it names any."""
        name = cell(stage["stage"][lang])
        if stage.get("roles"):
            roles = ", ".join(cell(self.content.roles[r]["name"][lang]) for r in stage["roles"])
            name += f"<br>*{roles}*"
        return name

    # AI roles

    def role_text(self, text: str, lang: str, page: str) -> str:
        """Role-guide prose with its [label](kind:id) links resolved for this page."""

        def link(match) -> str:
            label, kind, target = match.groups()
            if kind == "question":
                theme = self.question_by_id[target]["theme"]
                href = f"{rel(page, theme_page(lang, theme))}#{target}"
            elif kind == "theme":
                href = rel(page, theme_page(lang, target))
            elif kind == "role":
                href = rel(page, role_page(lang, target))
            else:
                href = rel(page, ROLE_PAGE_PATHS[target](lang))
            return f"[{label}]({href})"

        return ROLE_LINK.sub(link, md(text))

    def role_pages_line(self, lang: str, page: str, track: str) -> list[str]:
        """A nested list item linking the role pages of one track."""
        families = [
            f
            for f in self.content.families
            if any(self.content.roles[r]["track"] == track for r in f["roles"])
        ]
        if not families:
            return []
        links = " · ".join(
            f"[{f['name'][lang]}]({rel(page, role_page(lang, f['id']))})" for f in families
        )
        return [f"  - {LABELS[lang]['role_pages']}: {links}"]

    def family_stages(self, family: dict, lang: str) -> list[tuple[dict, dict]]:
        """(company, stage) pairs reported for the family's roles, in company page order."""
        roles = set(family["roles"])
        return [
            (company, stage)
            for company in self.companies_in_order(lang)
            for stage in company["loop"]
            if stage["claim"] != "assumption" and roles & set(stage.get("roles", []))
        ]

    def family_companies(self, family: dict, lang: str) -> list[dict]:
        """Companies whose pages list one of the family's roles."""
        roles = set(family["roles"])
        return [
            company
            for company in self.companies_in_order(lang)
            if roles & {role for ids in company["roles"].values() for role in ids}
        ]

    def family_questions(self, family: dict) -> tuple[list[dict], list[dict]]:
        """Questions reported for the family's roles, then those tagged only for practice."""
        roles = set(family["roles"])
        reported = [
            q
            for q in self.content.questions
            if roles & {item.get("role") for item in q.get("evidence", [])}
        ]
        seen = {q["id"] for q in reported}
        practice = [
            q
            for q in self.content.questions
            if q["id"] not in seen and roles & set(q.get("roles", []))
        ]

        def order(question: dict) -> int:
            return self.theme_order[question["theme"]]

        return sorted(reported, key=order), sorted(practice, key=order)

    def roles_overview(self, lang: str) -> str:
        labels, guide, page = LABELS[lang], self.content.guide, roles_page(lang)
        lines = [
            HEADER,
            f"# {labels['roles_title']}",
            "",
            self.header(lang, page, roles_page(other(lang)), "tracks"),
        ]
        for text in guide["intro"]:
            lines += ["", self.role_text(text[lang], lang, page)]
        lines += [
            "",
            labels["roles_checked"].format(date=guide["checked"]),
            "",
            labels["legend"],
            "",
            (
                f"| {labels['role_family']} | {labels['role_owns']} | {labels['role_stages']} "
                f"| {labels['role_companies']} | {labels['role_reported_count']} "
                f"| {labels['role_practice_count']} |"
            ),
            "| --- | --- | ---: | ---: | ---: | ---: |",
        ]
        for family in self.content.families:
            reported, practice = self.family_questions(family)
            stages = self.family_stages(family, lang)
            companies = len({company["id"] for company, _ in stages})
            link = rel(page, role_page(lang, family["id"]))
            lines.append(
                f"| [{cell(family['name'][lang])}]({link}) | {cell(family['summary'][lang])} "
                f"| {len(stages)} | {companies} | {len(reported)} | {len(practice)} |"
            )
        return "\n".join(lines)

    def role(self, lang: str, family: dict) -> str:
        labels, content = LABELS[lang], self.content
        page = role_page(lang, family["id"])
        reported, practice = self.family_questions(family)
        stages = self.family_stages(family, lang)
        roles = ", ".join(content.roles[r]["name"][lang] for r in family["roles"])
        tracks = " / ".join(
            self.track_names[track][lang]
            for track in TRACKS
            if any(content.roles[r]["track"] == track for r in family["roles"])
        )
        contents = [
            f"[{labels['role_scope']}](#scope)",
            f"[{labels['role_interviews']} ({len(stages)})](#interviews)",
            f"[{labels['questions']} ({len(reported) + len(practice)})](#role-questions)",
            f"[{labels['role_prep']}](#prep)",
        ]
        lines = [
            HEADER,
            f"# {family['name'][lang]}",
            "",
            self.header(lang, page, role_page(other(lang), family["id"]), "roles"),
            "",
            f"{tracks} · {labels['roles']}: {roles}",
            "",
            md(family["summary"][lang]),
            "",
            f"{labels['on_page']}: " + " · ".join(contents),
            "",
            f"## {anchor('scope')}{labels['role_scope']}",
        ]
        for section in family["sections"]:
            lines += ["", self.role_text(section["text"][lang], lang, page)]
            if section.get("sources"):
                cited = " · ".join(self.source_link(s, lang) for s in section["sources"])
                lines += ["", f"{labels['role_sources']}: {cited}"]
        lines += ["", f"## {anchor('interviews')}{labels['role_interviews']}", ""]
        if stages:
            lines += [
                labels["role_interviews_intro"],
                "",
                (
                    f"| {labels['company']} | {labels['stage']} | {labels['what']} "
                    f"| {labels['basis']} |"
                ),
                "| --- | --- | --- | --- |",
            ]
            for company, stage in stages:
                basis = [labels["claims"][stage["claim"]]]
                basis += [self.source_link(s, lang) for s in stage.get("sources", [])]
                detail = cell(stage["detail"][lang]) if stage.get("detail") else ""
                name = f"[{cell(company['name'][lang])}]({rel(page, company_page(lang, company['id']))})"
                lines.append(
                    f"| {name} | {self.stage_name(stage, lang)} | {detail} | {'<br>'.join(basis)} |"
                )
        else:
            lines.append(labels["role_no_interviews"])
        covering = self.family_companies(family, lang)
        if covering:
            links = ", ".join(
                f"[{c['name'][lang]}]({rel(page, company_page(lang, c['id']))})" for c in covering
            )
            lines += ["", labels["role_company_pages"].format(links=links)]
        lines += ["", f"## {anchor('role-questions')}{labels['questions']}"]
        if not reported and not practice:
            lines += ["", labels["role_no_questions"]]
        for title, intro, chosen in (
            (labels["role_reported"], labels["role_reported_intro"], reported),
            (labels["role_practice"], labels["role_practice_intro"], practice),
        ):
            if chosen:
                lines += ["", f"### {title}", "", intro, ""]
                for question in chosen:
                    evidence = [
                        e for e in question.get("evidence", []) if e.get("role") in family["roles"]
                    ]
                    scoped = {**question, "evidence": evidence}
                    lines += self.question(scoped, lang, page, full=False, theme_link=True)
                    for source_id, role in dict.fromkeys(
                        (e["source"], e["role"]) for e in evidence
                    ):
                        kind = content.sources[source_id]["kind"]
                        role_name = content.roles[role]["name"][lang]
                        lines.append(
                            f"  - {labels['role_sources']} ({role_name}): "
                            f"{MARKERS[kind]} {self.source_link(source_id, lang)}"
                        )
        lines += [
            "",
            f"## {anchor('prep')}{labels['role_prep']}",
            "",
            f"**{labels['role_route']}:** {self.role_text(family['prep'][lang], lang, page)}",
        ]
        if family.get("practice"):
            practice_text = self.role_text(family["practice"][lang], lang, page)
            lines += ["", f"**{labels['role_deliverable']}:** {practice_text}"]
        order = [(f["name"][lang], role_page(lang, f["id"])) for f in content.families]
        lines += self.pager(page, order, page)
        return "\n".join(lines)

    def source_link(self, source_id: str, lang: str) -> str:
        source, labels = self.content.sources[source_id], LABELS[lang]
        parts = [f"[{cell(source['title'])}]({source['url']})", cell(source["publisher"])]
        if source.get("published"):
            parts.append(f"{labels['published']} {source['published']}")
        parts.append(f"{labels['retrieved']} {source['retrieved']}")
        return ", ".join(parts)

    def sources(self, lang: str) -> str:
        labels, page = LABELS[lang], sources_page(lang)
        lines = [
            HEADER,
            f"# {labels['sources_title']}",
            "",
            self.header(lang, page, sources_page(other(lang)), "reference"),
        ]
        by_kind = {kind: [] for kind in SOURCE_KINDS}
        for source in self.content.sources.values():
            by_kind[source["kind"]].append(source)
        licensed = sorted(
            (s for s in by_kind["secondary_compilation"] if s.get("license")),
            key=lambda s: s["id"],
        )
        if licensed:
            lines.append("")
            for source in licensed:
                lines.append(
                    labels["attribution"].format(
                        title=f"[{cell(source['title'])}]({source['url']})",
                        publisher=cell(source["publisher"]),
                        license=source["license"],
                    )
                )
        for kind in SOURCE_KINDS:
            chosen = sorted(
                by_kind[kind], key=lambda s: (s["publisher"].casefold(), s["title"].casefold())
            )
            if not chosen:
                continue
            kind_anchor = anchor(f"kind-{kind.replace('_', '-')}")
            lines += ["", f"## {kind_anchor}{labels['kinds'][kind]}", ""]
            for source in chosen:
                parts = [f"[{cell(source['title'])}]({source['url']})", cell(source["publisher"])]
                if source.get("published"):
                    parts.append(f"{labels['published']} {source['published']}")
                parts.append(f"{labels['retrieved']} {source['retrieved']}")
                if source.get("license"):
                    parts.append(f"{labels['license']} {source['license']}")
                line = "- " + " · ".join(parts)
                if source.get("note"):
                    line += f". {md(source['note'][lang])}"
                lines.append(line)
        return "\n".join(lines)

    def ai_share(self, lang: str) -> list[str]:
        radar, lines = self.content.radar, []
        for track in TRACKS:
            count = radar.get("ai_mentions", {}).get(track)
            if count:
                total = radar["sample"]["tracks"][track]
                lines.append(
                    LABELS[lang]["ai_share"].format(
                        share=percent(count, total),
                        track=LABELS[lang]["sample_names"][track],
                        count=count,
                        total=total,
                    )
                )
        return lines

    def radar_cells(self) -> list[tuple[dict, dict[str, dict | None]]]:
        radar = self.content.radar
        rows = {(row["track"], row["theme"]): row for row in radar["rows"]}
        result = []
        for theme in self.content.taxonomy["themes"]:
            cells = {track: rows.get((track, theme["id"])) for track in TRACKS}
            if any(cells.values()):
                result.append((theme, cells))
        return result

    def radar(self, lang: str) -> str:
        labels, radar, page = LABELS[lang], self.content.radar, radar_page(lang)
        sample = radar["sample"]
        names = {track: self.track_names[track][lang] for track in TRACKS}
        lines = [
            HEADER,
            f"# {labels['radar_title']}",
            "",
            self.header(lang, page, radar_page(other(lang)), "reference"),
            "",
            f"- **{labels['period']}:** {radar['period']['from']} — {radar['period']['to']}",
            f"- **{labels['sample']}:** "
            + labels["sample_value"].format(
                postings=sample["postings"],
                engineering=sample["tracks"].get("engineering", 0),
                leadership=sample["tracks"].get("leadership", 0),
            )
            + "; "
            + labels["market_value"].format(
                intl=sample["markets"].get("intl", 0),
                ru=sample["markets"].get("ru", 0),
                unknown=sample["markets"].get("unknown", 0),
            ),
            "",
            f"![{labels['svg_title']}]({rel(page, svg_file(lang))})",
            "",
            f"| {labels['theme']} | {names['engineering']} | {names['leadership']} |",
            "| --- | ---: | ---: |",
        ]
        for theme, cells in self.radar_cells():
            values = []
            for track in TRACKS:
                row = cells[track]
                total = sample["tracks"].get(track, 0)
                values.append(
                    labels["share"].format(
                        share=percent(row["postings"], total), postings=row["postings"]
                    )
                    if row
                    else "—"
                )
            link = rel(page, theme_page(lang, theme["id"]))
            lines.append(f"| [{cell(theme['name'][lang])}]({link}) | {values[0]} | {values[1]} |")
        lines += ["", *self.ai_share(lang)] if self.ai_share(lang) else []
        lines += [
            "",
            labels["suppressed"].format(min_cell=radar["min_cell"], min_track=radar["min_track"]),
            "",
            f"## {labels['method']}",
            "",
            md(radar["method"][lang]),
        ]
        if radar.get("criteria"):
            lines += ["", f"### {labels['criteria']}", ""]
            for theme in self.content.taxonomy["themes"]:
                criterion = radar["criteria"].get(theme["id"])
                if criterion:
                    lines.append(f"- **{theme['name'][lang]}:** {md(criterion[lang])}")
        return "\n".join(lines)

    def svg(self, lang: str) -> str:
        labels, sample = LABELS[lang], self.content.radar["sample"]
        cells = self.radar_cells()
        label_width, bar_width, row_height, top = 300, 380, 34, 70
        width = label_width + bar_width + 80
        height = top + row_height * len(cells) + 90
        font = 'font-family="Segoe UI, Helvetica, Arial, sans-serif"'
        parts = [
            (
                f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" '
                f'viewBox="0 0 {width} {height}" role="img" '
                f'aria-label="{escape(labels["svg_title"], {chr(34): "&quot;"})}">'
            ),
            f"<title>{escape(labels['svg_title'])}</title>",
            (
                f'<rect x="0.5" y="0.5" width="{width - 1}" height="{height - 1}" rx="8" '
                'fill="#f6f8fa" stroke="#d0d7de"/>'
            ),
            (
                f'<text x="16" y="28" {font} font-size="16" font-weight="600" fill="#1f2328">'
                f"{escape(labels['svg_title'])}</text>"
            ),
        ]
        x = 16
        for track in TRACKS:
            name = escape(self.track_names[track][lang])
            parts.append(f'<rect x="{x}" y="42" width="12" height="12" fill="{COLORS[track]}"/>')
            parts.append(
                f'<text x="{x + 18}" y="53" {font} font-size="13" fill="#1f2328">{name}</text>'
            )
            x += 200
        for index, (theme, row_cells) in enumerate(cells):
            y = top + index * row_height
            parts.append(
                f'<text x="{label_width - 10}" y="{y + 17}" {font} font-size="13" '
                f'text-anchor="end" fill="#1f2328">{escape(theme["name"][lang])}</text>'
            )
            for offset, track in enumerate(TRACKS):
                row = row_cells[track]
                bar_y = y + 4 + offset * 13
                if not row:
                    parts.append(
                        f'<text x="{label_width}" y="{bar_y + 10}" {font} font-size="11" '
                        'fill="#59636e">—</text>'
                    )
                    continue
                share = percent(row["postings"], sample["tracks"].get(track, 0))
                length = max(1, round(bar_width * share / 100))
                parts.append(
                    f'<rect x="{label_width}" y="{bar_y}" width="{length}" height="11" '
                    f'fill="{COLORS[track]}"/>'
                )
                parts.append(
                    f'<text x="{label_width + length + 6}" y="{bar_y + 10}" {font} '
                    f'font-size="11" fill="#1f2328">{share}%</text>'
                )
        radar = self.content.radar
        denominators = "; ".join(
            f"{labels['sample_names'][track]} n={sample['tracks'].get(track, 0)}"
            for track in TRACKS
        )
        footer = [
            denominators,
            (
                f"— = suppressed, not zero (track n < {radar['min_track']} or theme n < {radar['min_cell']})."
                if lang == "en"
                else f"— = скрыто, не ноль (трек n < {radar['min_track']} или тема n < {radar['min_cell']})."
            ),
            f"{radar['period']['from']} — {radar['period']['to']}",
        ]
        for index, line in enumerate(footer):
            y = top + row_height * len(cells) + 22 + index * 20
            parts.append(
                f'<text x="16" y="{y}" {font} font-size="12" fill="#59636e">{escape(line)}</text>'
            )
        parts.append("</svg>")
        return "\n".join(parts)


def render(content: Content) -> dict[str, str]:
    """Every generated file, keyed by its path relative to the repository root."""
    return Renderer(content).pages()
